package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BDC2FC_DIRECTORY generated by hbm2java
 */
@Entity
@Table(name = "BDC2FC_DIRECTORY", schema = "GXDJK")
public class BDC2FC_DIRECTORY implements java.io.Serializable {

	private String id;
	private String bdcdirname;
	private String bdcdirvalue;
	private String bdcdir_desc;
	private String fcdirname;
	private String fcdirvalue;
	private String fcdir_desc;

	public BDC2FC_DIRECTORY() {
	}

	public BDC2FC_DIRECTORY(String id) {
		this.id = id;
	}

	public BDC2FC_DIRECTORY(String id, String bdcdirname, String bdcdirvalue,
			String bdcdir_desc, String fcdirname, String fcdirvalue,
			String fcdir_desc) {
		this.id = id;
		this.bdcdirname = bdcdirname;
		this.bdcdirvalue = bdcdirvalue;
		this.bdcdir_desc = bdcdir_desc;
		this.fcdirname = fcdirname;
		this.fcdirvalue = fcdirvalue;
		this.fcdir_desc = fcdir_desc;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		if (id == null)
			id = UUID.randomUUID().toString().replace("-", "");
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "BDCDIRNAME", length = 200)
	public String getBdcdirname() {
		return this.bdcdirname;
	}

	public void setBdcdirname(String bdcdirname) {
		this.bdcdirname = bdcdirname;
	}

	@Column(name = "BDCDIRVALUE", length = 200)
	public String getBdcdirvalue() {
		return this.bdcdirvalue;
	}

	public void setBdcdirvalue(String bdcdirvalue) {
		this.bdcdirvalue = bdcdirvalue;
	}

	@Column(name = "BDCDIR_DESC", length = 200)
	public String getBdcdir_desc() {
		return this.bdcdir_desc;
	}

	public void setBdcdir_desc(String bdcdir_desc) {
		this.bdcdir_desc = bdcdir_desc;
	}

	@Column(name = "FCDIRNAME", length = 200)
	public String getFcdirname() {
		return this.fcdirname;
	}

	public void setFcdirname(String fcdirname) {
		this.fcdirname = fcdirname;
	}

	@Column(name = "FCDIRVALUE", length = 200)
	public String getFcdirvalue() {
		return this.fcdirvalue;
	}

	public void setFcdirvalue(String fcdirvalue) {
		this.fcdirvalue = fcdirvalue;
	}


	@Column(name = "FCDIR_DESC", length = 200)
	public String getFcdir_desc() {
		return this.fcdir_desc;
	}

	public void setFcdir_desc(String fcdir_desc) {
		this.fcdir_desc = fcdir_desc;
	}
}
