package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BdcsConst generated by hbm2java
 */
@Entity
@Table(name = "BDCS_CONST", schema = "GXDJK")
public class BdcsConst_dj implements java.io.Serializable {

    private BigDecimal mbbsm;
    private BigDecimal constslsid;
    private String constvalue;
    private String consttrans;
    private BigDecimal parentnode;
    private BigDecimal constorder;
    private String bz;
    private Date createtime;
    private Date modifytime;

    public BdcsConst_dj() {
    }

    public BdcsConst_dj(BigDecimal mbbsm) {
	this.mbbsm = mbbsm;
    }

    public BdcsConst_dj(BigDecimal mbbsm, BigDecimal constslsid,
	    String constvalue, String consttrans, BigDecimal parentnode,
	    BigDecimal constorder, String bz, Date createtime, Date modifytime) {
	this.mbbsm = mbbsm;
	this.constslsid = constslsid;
	this.constvalue = constvalue;
	this.consttrans = consttrans;
	this.parentnode = parentnode;
	this.constorder = constorder;
	this.bz = bz;
	this.createtime = createtime;
	this.modifytime = modifytime;
    }

    @Id
    @Column(name = "MBBSM", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getMbbsm() {
	return this.mbbsm;
    }

    public void setMbbsm(BigDecimal mbbsm) {
	this.mbbsm = mbbsm;
    }

    @Column(name = "CONSTSLSID", precision = 22, scale = 0)
    public BigDecimal getConstslsid() {
	return this.constslsid;
    }

    public void setConstslsid(BigDecimal constslsid) {
	this.constslsid = constslsid;
    }

    @Column(name = "CONSTVALUE", length = 200)
    public String getConstvalue() {
	return this.constvalue;
    }

    public void setConstvalue(String constvalue) {
	this.constvalue = constvalue;
    }

    @Column(name = "CONSTTRANS", length = 200)
    public String getConsttrans() {
	return this.consttrans;
    }

    public void setConsttrans(String consttrans) {
	this.consttrans = consttrans;
    }

    @Column(name = "PARENTNODE", precision = 22, scale = 0)
    public BigDecimal getParentnode() {
	return this.parentnode;
    }

    public void setParentnode(BigDecimal parentnode) {
	this.parentnode = parentnode;
    }

    @Column(name = "CONSTORDER", precision = 38, scale = 0)
    public BigDecimal getConstorder() {
	return this.constorder;
    }

    public void setConstorder(BigDecimal constorder) {
	this.constorder = constorder;
    }

    @Column(name = "BZ", length = 200)
    public String getBz() {
	return this.bz;
    }

    public void setBz(String bz) {
	this.bz = bz;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATETIME", length = 7)
    public Date getCreatetime() {
	return this.createtime;
    }

    public void setCreatetime(Date createtime) {
	this.createtime = createtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "MODIFYTIME", length = 7)
    public Date getModifytime() {
	return this.modifytime;
    }

    public void setModifytime(Date modifytime) {
	this.modifytime = modifytime;
    }

}
