package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Bgqh generated by hbm2java
 */
@Entity
@Table(name = "BGQH", schema = "GXDJK")
public class Bgqh_dj implements java.io.Serializable {

    private String bsm;
    private String bdcdyid;
    private String ysdm;
    private String bdcdyh;
    private String fwbm;
    private String zrzbdcdyid;
    private String zrzh;
    private String ljzid;
    private String ljzh;
    private String cid;
    private String ch;
    private String zl;
    private String mjdw;
    private BigDecimal sjcs;
    private String szc;
    private BigDecimal hh;
    private String shbw;
    private String hx;
    private String hxjg;
    private String fwyt1;
    private String fwyt2;
    private String fwyt3;
    private BigDecimal ycjzmj;
    private BigDecimal yctnjzmj;
    private BigDecimal ycftjzmj;
    private BigDecimal ycdxbfjzmj;
    private BigDecimal ycqtjzmj;
    private BigDecimal ycftxs;
    private BigDecimal scjzmj;
    private BigDecimal sctnjzmj;
    private BigDecimal scftjzmj;
    private BigDecimal scdxbfjzmj;
    private BigDecimal scqtjzmj;
    private BigDecimal scftxs;
    private BigDecimal gytdmj;
    private BigDecimal fttdmj;
    private BigDecimal dytdmj;
    private String ghyt;
    private String fwjg;
    private String fwlx;
    private String fwxz;
    private String fcfht;
    private BigDecimal zt;
    private String xmmc;
    private String relationid;
    private String gxxmbh;
    private String fwzt;
    private BigDecimal zcs;
    private Date jgsj;
    private String dyh;
    private String fh;
    private Date tssj;

    public Bgqh_dj() {
    }

    public Bgqh_dj(String bsm, String bdcdyid) {
	this.bsm = bsm;
	this.bdcdyid = bdcdyid;
    }

    public Bgqh_dj(String bsm, String bdcdyid, String ysdm, String bdcdyh,
	    String fwbm, String zrzbdcdyid, String zrzh, String ljzid,
	    String ljzh, String cid, String ch, String zl, String mjdw,
	    BigDecimal sjcs, String szc, BigDecimal hh, String shbw, String hx,
	    String hxjg, String fwyt1, String fwyt2, String fwyt3,
	    BigDecimal ycjzmj, BigDecimal yctnjzmj, BigDecimal ycftjzmj,
	    BigDecimal ycdxbfjzmj, BigDecimal ycqtjzmj, BigDecimal ycftxs,
	    BigDecimal scjzmj, BigDecimal sctnjzmj, BigDecimal scftjzmj,
	    BigDecimal scdxbfjzmj, BigDecimal scqtjzmj, BigDecimal scftxs,
	    BigDecimal gytdmj, BigDecimal fttdmj, BigDecimal dytdmj,
	    String ghyt, String fwjg, String fwlx, String fwxz, String fcfht,
	    BigDecimal zt, String xmmc, String relationid, String gxxmbh,
	    String fwzt, BigDecimal zcs, Date jgsj, String dyh, String fh,Date tssj) {
	this.bsm = bsm;
	this.bdcdyid = bdcdyid;
	this.ysdm = ysdm;
	this.bdcdyh = bdcdyh;
	this.fwbm = fwbm;
	this.zrzbdcdyid = zrzbdcdyid;
	this.zrzh = zrzh;
	this.ljzid = ljzid;
	this.ljzh = ljzh;
	this.cid = cid;
	this.ch = ch;
	this.zl = zl;
	this.mjdw = mjdw;
	this.sjcs = sjcs;
	this.szc = szc;
	this.hh = hh;
	this.shbw = shbw;
	this.hx = hx;
	this.hxjg = hxjg;
	this.fwyt1 = fwyt1;
	this.fwyt2 = fwyt2;
	this.fwyt3 = fwyt3;
	this.ycjzmj = ycjzmj;
	this.yctnjzmj = yctnjzmj;
	this.ycftjzmj = ycftjzmj;
	this.ycdxbfjzmj = ycdxbfjzmj;
	this.ycqtjzmj = ycqtjzmj;
	this.ycftxs = ycftxs;
	this.scjzmj = scjzmj;
	this.sctnjzmj = sctnjzmj;
	this.scftjzmj = scftjzmj;
	this.scdxbfjzmj = scdxbfjzmj;
	this.scqtjzmj = scqtjzmj;
	this.scftxs = scftxs;
	this.gytdmj = gytdmj;
	this.fttdmj = fttdmj;
	this.dytdmj = dytdmj;
	this.ghyt = ghyt;
	this.fwjg = fwjg;
	this.fwlx = fwlx;
	this.fwxz = fwxz;
	this.fcfht = fcfht;
	this.zt = zt;
	this.xmmc = xmmc;
	this.relationid = relationid;
	this.gxxmbh = gxxmbh;
	this.fwzt = fwzt;
	this.zcs = zcs;
	this.jgsj = jgsj;
	this.dyh = dyh;
	this.fh = fh;
	this.tssj = tssj;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	 if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "BDCDYID", nullable = false, length = 100)
    public String getBdcdyid() {
	return this.bdcdyid;
    }

    public void setBdcdyid(String bdcdyid) {
	this.bdcdyid = bdcdyid;
    }

    @Column(name = "YSDM", length = 20)
    public String getYsdm() {
	return this.ysdm;
    }

    public void setYsdm(String ysdm) {
	this.ysdm = ysdm;
    }

    @Column(name = "BDCDYH", length = 100)
    public String getBdcdyh() {
	return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
	this.bdcdyh = bdcdyh;
    }

    @Column(name = "FWBM", length = 100)
    public String getFwbm() {
	return this.fwbm;
    }

    public void setFwbm(String fwbm) {
	this.fwbm = fwbm;
    }

    @Column(name = "ZRZBDCDYID", length = 100)
    public String getZrzbdcdyid() {
	return this.zrzbdcdyid;
    }

    public void setZrzbdcdyid(String zrzbdcdyid) {
	this.zrzbdcdyid = zrzbdcdyid;
    }

    @Column(name = "ZRZH", length = 100)
    public String getZrzh() {
	return this.zrzh;
    }

    public void setZrzh(String zrzh) {
	this.zrzh = zrzh;
    }

    @Column(name = "LJZID", length = 100)
    public String getLjzid() {
	return this.ljzid;
    }

    public void setLjzid(String ljzid) {
	this.ljzid = ljzid;
    }

    @Column(name = "LJZH", length = 100)
    public String getLjzh() {
	return this.ljzh;
    }

    public void setLjzh(String ljzh) {
	this.ljzh = ljzh;
    }

    @Column(name = "CID", length = 100)
    public String getCid() {
	return this.cid;
    }

    public void setCid(String cid) {
	this.cid = cid;
    }

    @Column(name = "CH", length = 40)
    public String getCh() {
	return this.ch;
    }

    public void setCh(String ch) {
	this.ch = ch;
    }

    @Column(name = "ZL", length = 400)
    public String getZl() {
	return this.zl;
    }

    public void setZl(String zl) {
	this.zl = zl;
    }

    @Column(name = "MJDW", length = 20)
    public String getMjdw() {
	return this.mjdw;
    }

    public void setMjdw(String mjdw) {
	this.mjdw = mjdw;
    }

    @Column(name = "SJCS", precision = 38, scale = 16)
    public BigDecimal getSjcs() {
	return this.sjcs;
    }

    public void setSjcs(BigDecimal sjcs) {
	this.sjcs = sjcs;
    }

    @Column(name = "SZC", length = 60)
    public String getSzc() {
	return this.szc;
    }

    public void setSzc(String szc) {
	this.szc = szc;
    }

    @Column(name = "HH", precision = 38, scale = 0)
    public BigDecimal getHh() {
	return this.hh;
    }

    public void setHh(BigDecimal hh) {
	this.hh = hh;
    }

    @Column(name = "SHBW", length = 40)
    public String getShbw() {
	return this.shbw;
    }

    public void setShbw(String shbw) {
	this.shbw = shbw;
    }

    @Column(name = "HX", length = 20)
    public String getHx() {
	return this.hx;
    }

    public void setHx(String hx) {
	this.hx = hx;
    }

    @Column(name = "HXJG", length = 20)
    public String getHxjg() {
	return this.hxjg;
    }

    public void setHxjg(String hxjg) {
	this.hxjg = hxjg;
    }

    @Column(name = "FWYT1", length = 20)
    public String getFwyt1() {
	return this.fwyt1;
    }

    public void setFwyt1(String fwyt1) {
	this.fwyt1 = fwyt1;
    }

    @Column(name = "FWYT2", length = 20)
    public String getFwyt2() {
	return this.fwyt2;
    }

    public void setFwyt2(String fwyt2) {
	this.fwyt2 = fwyt2;
    }

    @Column(name = "FWYT3", length = 20)
    public String getFwyt3() {
	return this.fwyt3;
    }

    public void setFwyt3(String fwyt3) {
	this.fwyt3 = fwyt3;
    }

    @Column(name = "YCJZMJ", precision = 38, scale = 16)
    public BigDecimal getYcjzmj() {
	return this.ycjzmj;
    }

    public void setYcjzmj(BigDecimal ycjzmj) {
	this.ycjzmj = ycjzmj;
    }

    @Column(name = "YCTNJZMJ", precision = 38, scale = 16)
    public BigDecimal getYctnjzmj() {
	return this.yctnjzmj;
    }

    public void setYctnjzmj(BigDecimal yctnjzmj) {
	this.yctnjzmj = yctnjzmj;
    }

    @Column(name = "YCFTJZMJ", precision = 38, scale = 16)
    public BigDecimal getYcftjzmj() {
	return this.ycftjzmj;
    }

    public void setYcftjzmj(BigDecimal ycftjzmj) {
	this.ycftjzmj = ycftjzmj;
    }

    @Column(name = "YCDXBFJZMJ", precision = 38, scale = 16)
    public BigDecimal getYcdxbfjzmj() {
	return this.ycdxbfjzmj;
    }

    public void setYcdxbfjzmj(BigDecimal ycdxbfjzmj) {
	this.ycdxbfjzmj = ycdxbfjzmj;
    }

    @Column(name = "YCQTJZMJ", precision = 38, scale = 16)
    public BigDecimal getYcqtjzmj() {
	return this.ycqtjzmj;
    }

    public void setYcqtjzmj(BigDecimal ycqtjzmj) {
	this.ycqtjzmj = ycqtjzmj;
    }

    @Column(name = "YCFTXS", precision = 38, scale = 16)
    public BigDecimal getYcftxs() {
	return this.ycftxs;
    }

    public void setYcftxs(BigDecimal ycftxs) {
	this.ycftxs = ycftxs;
    }

    @Column(name = "SCJZMJ", precision = 38, scale = 16)
    public BigDecimal getScjzmj() {
	return this.scjzmj;
    }

    public void setScjzmj(BigDecimal scjzmj) {
	this.scjzmj = scjzmj;
    }

    @Column(name = "SCTNJZMJ", precision = 38, scale = 16)
    public BigDecimal getSctnjzmj() {
	return this.sctnjzmj;
    }

    public void setSctnjzmj(BigDecimal sctnjzmj) {
	this.sctnjzmj = sctnjzmj;
    }

    @Column(name = "SCFTJZMJ", precision = 38, scale = 16)
    public BigDecimal getScftjzmj() {
	return this.scftjzmj;
    }

    public void setScftjzmj(BigDecimal scftjzmj) {
	this.scftjzmj = scftjzmj;
    }

    @Column(name = "SCDXBFJZMJ", precision = 38, scale = 16)
    public BigDecimal getScdxbfjzmj() {
	return this.scdxbfjzmj;
    }

    public void setScdxbfjzmj(BigDecimal scdxbfjzmj) {
	this.scdxbfjzmj = scdxbfjzmj;
    }

    @Column(name = "SCQTJZMJ", precision = 38, scale = 16)
    public BigDecimal getScqtjzmj() {
	return this.scqtjzmj;
    }

    public void setScqtjzmj(BigDecimal scqtjzmj) {
	this.scqtjzmj = scqtjzmj;
    }

    @Column(name = "SCFTXS", precision = 38, scale = 16)
    public BigDecimal getScftxs() {
	return this.scftxs;
    }

    public void setScftxs(BigDecimal scftxs) {
	this.scftxs = scftxs;
    }

    @Column(name = "GYTDMJ", precision = 38, scale = 16)
    public BigDecimal getGytdmj() {
	return this.gytdmj;
    }

    public void setGytdmj(BigDecimal gytdmj) {
	this.gytdmj = gytdmj;
    }

    @Column(name = "FTTDMJ", precision = 38, scale = 16)
    public BigDecimal getFttdmj() {
	return this.fttdmj;
    }

    public void setFttdmj(BigDecimal fttdmj) {
	this.fttdmj = fttdmj;
    }

    @Column(name = "DYTDMJ", precision = 38, scale = 16)
    public BigDecimal getDytdmj() {
	return this.dytdmj;
    }

    public void setDytdmj(BigDecimal dytdmj) {
	this.dytdmj = dytdmj;
    }

    @Column(name = "GHYT", length = 20)
    public String getGhyt() {
	return this.ghyt;
    }

    public void setGhyt(String ghyt) {
	this.ghyt = ghyt;
    }

    @Column(name = "FWJG", length = 20)
    public String getFwjg() {
	return this.fwjg;
    }

    public void setFwjg(String fwjg) {
	this.fwjg = fwjg;
    }

    @Column(name = "FWLX", length = 20)
    public String getFwlx() {
	return this.fwlx;
    }

    public void setFwlx(String fwlx) {
	this.fwlx = fwlx;
    }

    @Column(name = "FWXZ", length = 20)
    public String getFwxz() {
	return this.fwxz;
    }

    public void setFwxz(String fwxz) {
	this.fwxz = fwxz;
    }

    @Column(name = "FCFHT", length = 100)
    public String getFcfht() {
	return this.fcfht;
    }

    public void setFcfht(String fcfht) {
	this.fcfht = fcfht;
    }

    @Column(name = "ZT", precision = 38, scale = 0)
    public BigDecimal getZt() {
	return this.zt;
    }

    public void setZt(BigDecimal zt) {
	this.zt = zt;
    }

    @Column(name = "XMMC", length = 400)
    public String getXmmc() {
	return this.xmmc;
    }

    public void setXmmc(String xmmc) {
	this.xmmc = xmmc;
    }

    @Column(name = "RELATIONID", length = 100)
    public String getRelationid() {
	return this.relationid;
    }

    public void setRelationid(String relationid) {
	this.relationid = relationid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

    @Column(name = "FWZT", length = 20)
    public String getFwzt() {
	return this.fwzt;
    }

    public void setFwzt(String fwzt) {
	this.fwzt = fwzt;
    }

    @Column(name = "ZCS", precision = 38, scale = 0)
    public BigDecimal getZcs() {
	return this.zcs;
    }

    public void setZcs(BigDecimal zcs) {
	this.zcs = zcs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "JGSJ", length = 7)
    public Date getJgsj() {
	return this.jgsj;
    }

    public void setJgsj(Date jgsj) {
	this.jgsj = jgsj;
    }

    @Column(name = "DYH", length = 200)
    public String getDyh() {
	return this.dyh;
    }

    public void setDyh(String dyh) {
	this.dyh = dyh;
    }

    @Column(name = "FH", length = 200)
    public String getFh() {
	return this.fh;
    }

    public void setFh(String fh) {
	this.fh = fh;
    }

    @Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
	@Column(name = "TSSJ", length = 7)
	public Date getTssj() {
		return this.tssj;
	}

	public void setTssj(Date tssj) {
		this.tssj = tssj;
	}
}
