package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * C generated by hbm2java
 */
@Entity
@Table(name = "C", schema = "GXDJK", uniqueConstraints = @UniqueConstraint(columnNames = "CID"))
public class C_dj implements java.io.Serializable {

    private String bsm;
    private String cid;
    private String ysdm;
    private String ch;
    private String zrzbdcdyid;
    private String zrzh;
    private BigDecimal sjc;
    private String myc;
    private BigDecimal cjzmj;
    private BigDecimal ctnjzmj;
    private BigDecimal cytmj;
    private BigDecimal cgyjzmj;
    private BigDecimal cftjzmj;
    private BigDecimal cg;
    private BigDecimal sptymj;
    private BigDecimal cbqmj;
    private String ljzid;
    private String gxxmbh;

    public C_dj() {
    }

    public C_dj(String bsm, String cid) {
	this.bsm = bsm;
	this.cid = cid;
    }

    public C_dj(String bsm, String cid, String ysdm, String ch, String zrzbdcdyid,
	    String zrzh, BigDecimal sjc, String myc, BigDecimal cjzmj,
	    BigDecimal ctnjzmj, BigDecimal cytmj, BigDecimal cgyjzmj,
	    BigDecimal cftjzmj, BigDecimal cg, BigDecimal sptymj,
	    BigDecimal cbqmj, String ljzid, String gxxmbh) {
	this.bsm = bsm;
	this.cid = cid;
	this.ysdm = ysdm;
	this.ch = ch;
	this.zrzbdcdyid = zrzbdcdyid;
	this.zrzh = zrzh;
	this.sjc = sjc;
	this.myc = myc;
	this.cjzmj = cjzmj;
	this.ctnjzmj = ctnjzmj;
	this.cytmj = cytmj;
	this.cgyjzmj = cgyjzmj;
	this.cftjzmj = cftjzmj;
	this.cg = cg;
	this.sptymj = sptymj;
	this.cbqmj = cbqmj;
	this.ljzid = ljzid;
	this.gxxmbh = gxxmbh;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "CID", unique = true, nullable = false, length = 100)
    public String getCid() {
	return this.cid;
    }

    public void setCid(String cid) {
	this.cid = cid;
    }

    @Column(name = "YSDM", length = 20)
    public String getYsdm() {
	return this.ysdm;
    }

    public void setYsdm(String ysdm) {
	this.ysdm = ysdm;
    }

    @Column(name = "CH", length = 40)
    public String getCh() {
	return this.ch;
    }

    public void setCh(String ch) {
	this.ch = ch;
    }

    @Column(name = "ZRZBDCDYID", length = 100)
    public String getZrzbdcdyid() {
	return this.zrzbdcdyid;
    }

    public void setZrzbdcdyid(String zrzbdcdyid) {
	this.zrzbdcdyid = zrzbdcdyid;
    }

    @Column(name = "ZRZH", length = 40)
    public String getZrzh() {
	return this.zrzh;
    }

    public void setZrzh(String zrzh) {
	this.zrzh = zrzh;
    }

    @Column(name = "SJC", precision = 38, scale = 0)
    public BigDecimal getSjc() {
	return this.sjc;
    }

    public void setSjc(BigDecimal sjc) {
	this.sjc = sjc;
    }

    @Column(name = "MYC", length = 100)
    public String getMyc() {
	return this.myc;
    }

    public void setMyc(String myc) {
	this.myc = myc;
    }

    @Column(name = "CJZMJ", precision = 38, scale = 16)
    public BigDecimal getCjzmj() {
	return this.cjzmj;
    }

    public void setCjzmj(BigDecimal cjzmj) {
	this.cjzmj = cjzmj;
    }

    @Column(name = "CTNJZMJ", precision = 38, scale = 16)
    public BigDecimal getCtnjzmj() {
	return this.ctnjzmj;
    }

    public void setCtnjzmj(BigDecimal ctnjzmj) {
	this.ctnjzmj = ctnjzmj;
    }

    @Column(name = "CYTMJ", precision = 38, scale = 16)
    public BigDecimal getCytmj() {
	return this.cytmj;
    }

    public void setCytmj(BigDecimal cytmj) {
	this.cytmj = cytmj;
    }

    @Column(name = "CGYJZMJ", precision = 38, scale = 16)
    public BigDecimal getCgyjzmj() {
	return this.cgyjzmj;
    }

    public void setCgyjzmj(BigDecimal cgyjzmj) {
	this.cgyjzmj = cgyjzmj;
    }

    @Column(name = "CFTJZMJ", precision = 38, scale = 16)
    public BigDecimal getCftjzmj() {
	return this.cftjzmj;
    }

    public void setCftjzmj(BigDecimal cftjzmj) {
	this.cftjzmj = cftjzmj;
    }

    @Column(name = "CG", precision = 38, scale = 16)
    public BigDecimal getCg() {
	return this.cg;
    }

    public void setCg(BigDecimal cg) {
	this.cg = cg;
    }

    @Column(name = "SPTYMJ", precision = 38, scale = 16)
    public BigDecimal getSptymj() {
	return this.sptymj;
    }

    public void setSptymj(BigDecimal sptymj) {
	this.sptymj = sptymj;
    }

    @Column(name = "CBQMJ", precision = 38, scale = 16)
    public BigDecimal getCbqmj() {
	return this.cbqmj;
    }

    public void setCbqmj(BigDecimal cbqmj) {
	this.cbqmj = cbqmj;
    }

    @Column(name = "LJZID", length = 100)
    public String getLjzid() {
	return this.ljzid;
    }

    public void setLjzid(String ljzid) {
	this.ljzid = ljzid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

}
