package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Da generated by hbm2java
 */
@Entity
@Table(name = "DJ_FC_RELATION", schema = "BDC_WORKFLOW")
public class DJ_FC_RELATION implements java.io.Serializable {

    private String BSM;
    private String PROJECT_ID;
    private String LSH;
    private String ACTIVEID;
    private String GT_YWBH;
    private Date CREATETIME;
    private String SLD;
    public DJ_FC_RELATION(){
    	
    }
    public DJ_FC_RELATION(String bSM, String pROJECT_ID, String lSH, String aCTIVEID,
			String gT_YWBH, Date cREATETIME,String sLD) {
		super();
		BSM = bSM;
		PROJECT_ID = pROJECT_ID;
		LSH = lSH;
		ACTIVEID = aCTIVEID;
		GT_YWBH = gT_YWBH;
		CREATETIME = cREATETIME;
		SLD=sLD;
	}
    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
	public String getBSM() {
    	 if (BSM == null) BSM = UUID.randomUUID().toString().replace("-", ""); 
		return BSM;
	}
	public void setBSM(String bSM) {
		BSM = bSM;
	}
	 @Column(name = "PROJECT_ID", length = 100)
	public String getPROJECT_ID() {
		return PROJECT_ID;
	}
	public void setPROJECT_ID(String pROJECT_ID) {
		PROJECT_ID = pROJECT_ID;
	}
	 @Column(name = "LSH", length = 100)
	public String getLSH() {
		return LSH;
	}
	public void setLSH(String lSH) {
		LSH = lSH;
	}
	 @Column(name = "ACTIVEID", length = 100)
	public String getACTIVEID() {
		return ACTIVEID;
	}
	public void setACTIVEID(String aCTIVEID) {
		ACTIVEID = aCTIVEID;
	}
	 @Column(name = "GT_YWBH", length = 100)
	public String getGT_YWBH() {
		return GT_YWBH;
	}
	public void setGT_YWBH(String gT_YWBH) {
		GT_YWBH = gT_YWBH;
	} 
	 @Temporal(TemporalType.DATE)
	@Column(name = "CREATETIME", length = 200)
	public Date getCREATETIME() {
		return CREATETIME;
	}
	public void setCREATETIME(Date cREATETIME) {
		CREATETIME = cREATETIME;
	}
	@Column(name = "SLD", length = 20)
	public String getSLD() {
		return SLD;
	}
	public void setSLD(String sLD) {
		SLD = sLD;
	}
   
}
