package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Dyaq generated by hbm2java
 */
@Entity
@Table(name = "DYAQ", schema = "GXDJK")
public class Dyaq_dj implements java.io.Serializable {

    private String bsm;
    private String ywh;
    private String bdcdyh;
    private String qlid;
    private String djlx;
    private String djyy;
    private Date zwlxqssj;
    private Date zwlxjssj;
    private String bdcdjzmh;
    private String qxdm;
    private String djjg;
    private String dbr;
    private Date djsj;
    private String fj;
    private String qszt;
    private String bdcdyid;
    private String gxxmbh;
    private String dyfs;
    private BigDecimal bdbzzqse;
    private String zgzqqdss;
    private BigDecimal zgzqse;
    private String zxdyywh;
    private String zxdyyy;
    private Date zxsj;
    private String dybdclx;
    private String zjjzwzl;
    private String zjjzwdyfw;
    private String dyr;
    private String lyqlid;
    private String ysdm;
    private BigDecimal dymj;
    private String zsbh;
    private String bz;
    private String zxdbr;
    private Date tssj;
    public String getZxdbr() {
		return zxdbr;
	}

	public void setZxdbr(String zxdbr) {
		this.zxdbr = zxdbr;
	}

    public Dyaq_dj() {
    }

    public Dyaq_dj(String bsm) {
	this.bsm = bsm;
    }

    public Dyaq_dj(String bsm, String ywh, String bdcdyh, String qlid,
	    String djlx, String djyy, Date zwlxqssj, Date zwlxjssj,
	    String bdcdjzmh, String qxdm, String djjg, String dbr, Date djsj,
	    String fj, String qszt, String bdcdyid, String gxxmbh, String dyfs,
	    BigDecimal bdbzzqse, String zgzqqdss, BigDecimal zgzqse,
	    String zxdyywh, String zxdyyy, Date zxsj, String dybdclx,
	    String zjjzwzl, String zjjzwdyfw, String dyr, String lyqlid,
	    String ysdm, BigDecimal dymj, String zsbh, String bz,Date tssj) {
	this.bsm = bsm;
	this.ywh = ywh;
	this.bdcdyh = bdcdyh;
	this.qlid = qlid;
	this.djlx = djlx;
	this.djyy = djyy;
	this.zwlxqssj = zwlxqssj;
	this.zwlxjssj = zwlxjssj;
	this.bdcdjzmh = bdcdjzmh;
	this.qxdm = qxdm;
	this.djjg = djjg;
	this.dbr = dbr;
	this.djsj = djsj;
	this.fj = fj;
	this.qszt = qszt;
	this.bdcdyid = bdcdyid;
	this.gxxmbh = gxxmbh;
	this.dyfs = dyfs;
	this.bdbzzqse = bdbzzqse;
	this.zgzqqdss = zgzqqdss;
	this.zgzqse = zgzqse;
	this.zxdyywh = zxdyywh;
	this.zxdyyy = zxdyyy;
	this.zxsj = zxsj;
	this.dybdclx = dybdclx;
	this.zjjzwzl = zjjzwzl;
	this.zjjzwdyfw = zjjzwdyfw;
	this.dyr = dyr;
	this.lyqlid = lyqlid;
	this.ysdm = ysdm;
	this.dymj = dymj;
	this.zsbh = zsbh;
	this.bz = bz;
	this.tssj = tssj;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "YWH", length = 100)
    public String getYwh() {
	return this.ywh;
    }

    public void setYwh(String ywh) {
	this.ywh = ywh;
    }

    @Column(name = "BDCDYH", length = 100)
    public String getBdcdyh() {
	return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
	this.bdcdyh = bdcdyh;
    }

    @Column(name = "QLID", length = 100)
    public String getQlid() {
	return this.qlid;
    }

    public void setQlid(String qlid) {
	this.qlid = qlid;
    }

    @Column(name = "DJLX", length = 12)
    public String getDjlx() {
	return this.djlx;
    }

    public void setDjlx(String djlx) {
	this.djlx = djlx;
    }

    @Column(name = "DJYY", length = 100)
    public String getDjyy() {
	return this.djyy;
    }

    public void setDjyy(String djyy) {
	this.djyy = djyy;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "ZWLXQSSJ", length = 7)
    public Date getZwlxqssj() {
	return this.zwlxqssj;
    }

    public void setZwlxqssj(Date zwlxqssj) {
	this.zwlxqssj = zwlxqssj;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "ZWLXJSSJ", length = 7)
    public Date getZwlxjssj() {
	return this.zwlxjssj;
    }

    public void setZwlxjssj(Date zwlxjssj) {
	this.zwlxjssj = zwlxjssj;
    }

    @Column(name = "BDCDJZMH", length = 100)
    public String getBdcdjzmh() {
	return this.bdcdjzmh;
    }

    public void setBdcdjzmh(String bdcdjzmh) {
	this.bdcdjzmh = bdcdjzmh;
    }

    @Column(name = "QXDM", length = 12)
    public String getQxdm() {
	return this.qxdm;
    }

    public void setQxdm(String qxdm) {
	this.qxdm = qxdm;
    }

    @Column(name = "DJJG", length = 400)
    public String getDjjg() {
	return this.djjg;
    }

    public void setDjjg(String djjg) {
	this.djjg = djjg;
    }

    @Column(name = "DBR", length = 40)
    public String getDbr() {
	return this.dbr;
    }

    public void setDbr(String dbr) {
	this.dbr = dbr;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "DJSJ", length = 7)
    public Date getDjsj() {
	return this.djsj;
    }

    public void setDjsj(Date djsj) {
	this.djsj = djsj;
    }

    @Column(name = "FJ", length = 4000)
    public String getFj() {
	return this.fj;
    }

    public void setFj(String fj) {
	this.fj = fj;
    }

    @Column(name = "QSZT", length = 4)
    public String getQszt() {
	return this.qszt;
    }

    public void setQszt(String qszt) {
	this.qszt = qszt;
    }

    @Column(name = "BDCDYID", length = 100)
    public String getBdcdyid() {
	return this.bdcdyid;
    }

    public void setBdcdyid(String bdcdyid) {
	this.bdcdyid = bdcdyid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

    @Column(name = "DYFS", length = 20)
    public String getDyfs() {
	return this.dyfs;
    }

    public void setDyfs(String dyfs) {
	this.dyfs = dyfs;
    }

    @Column(name = "BDBZZQSE", precision = 38, scale = 16)
    public BigDecimal getBdbzzqse() {
	return this.bdbzzqse;
    }

    public void setBdbzzqse(BigDecimal bdbzzqse) {
	this.bdbzzqse = bdbzzqse;
    }

    @Column(name = "ZGZQQDSS", length = 400)
    public String getZgzqqdss() {
	return this.zgzqqdss;
    }

    public void setZgzqqdss(String zgzqqdss) {
	this.zgzqqdss = zgzqqdss;
    }

    @Column(name = "ZGZQSE", precision = 38, scale = 16)
    public BigDecimal getZgzqse() {
	return this.zgzqse;
    }

    public void setZgzqse(BigDecimal zgzqse) {
	this.zgzqse = zgzqse;
    }

    @Column(name = "ZXDYYWH", length = 100)
    public String getZxdyywh() {
	return this.zxdyywh;
    }

    public void setZxdyywh(String zxdyywh) {
	this.zxdyywh = zxdyywh;
    }

    @Column(name = "ZXDYYY", length = 2000)
    public String getZxdyyy() {
	return this.zxdyyy;
    }

    public void setZxdyyy(String zxdyyy) {
	this.zxdyyy = zxdyyy;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "ZXSJ", length = 7)
    public Date getZxsj() {
	return this.zxsj;
    }

    public void setZxsj(Date zxsj) {
	this.zxsj = zxsj;
    }

    @Column(name = "DYBDCLX", length = 20)
    public String getDybdclx() {
	return this.dybdclx;
    }

    public void setDybdclx(String dybdclx) {
	this.dybdclx = dybdclx;
    }

    @Column(name = "ZJJZWZL", length = 400)
    public String getZjjzwzl() {
	return this.zjjzwzl;
    }

    public void setZjjzwzl(String zjjzwzl) {
	this.zjjzwzl = zjjzwzl;
    }

    @Column(name = "ZJJZWDYFW", length = 400)
    public String getZjjzwdyfw() {
	return this.zjjzwdyfw;
    }

    public void setZjjzwdyfw(String zjjzwdyfw) {
	this.zjjzwdyfw = zjjzwdyfw;
    }

    @Column(name = "DYR", length = 4000)
    public String getDyr() {
	return this.dyr;
    }

    public void setDyr(String dyr) {
	this.dyr = dyr;
    }

    @Column(name = "LYQLID", length = 100)
    public String getLyqlid() {
	return this.lyqlid;
    }

    public void setLyqlid(String lyqlid) {
	this.lyqlid = lyqlid;
    }

    @Column(name = "YSDM", length = 100)
    public String getYsdm() {
	return this.ysdm;
    }

    public void setYsdm(String ysdm) {
	this.ysdm = ysdm;
    }

    @Column(name = "DYMJ", precision = 38, scale = 16)
    public BigDecimal getDymj() {
	return this.dymj;
    }

    public void setDymj(BigDecimal dymj) {
	this.dymj = dymj;
    }

    @Column(name = "ZSBH", length = 40)
    public String getZsbh() {
	return this.zsbh;
    }

    public void setZsbh(String zsbh) {
	this.zsbh = zsbh;
    }

    @Column(name = "BZ", length = 4000)
    public String getBz() {
	return this.bz;
    }

    public void setBz(String bz) {
	this.bz = bz;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
   	@Column(name = "TSSJ", length = 7)
   	public Date getTssj() {
   		return this.tssj;
   	}

   	public void setTssj(Date tssj) {
   		this.tssj = tssj;
   	}
}
