package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Fdcq generated by hbm2java
 */
@Entity
@Table(name = "FDCQZXDJ", schema = "GXDJK")
public class Fdcqzxdj_dj implements java.io.Serializable {

	 private String bsm;
	    private String ysdm;
	    private String bdcdyh;
	    private String ywh;
	    private String bdcqzh;
	    private String qxdm;
	    private String djjg;
	    private String dbr;
	    private Date djsj;
	    private String fj;
	    private BigDecimal qszt;
	    private String qlid;
	    private String bdcdyid;
	    private String gxxmbh;
	    private String zsbh;
	    private String bz;
	    private String czfs;
	    private String lyqlid;
	    private Date tssj;
	    
	    public String getLyqlid() {
			return lyqlid;
		}

		public void setLyqlid(String lyqlid) {
			this.lyqlid = lyqlid;
		}

		private String zxywh;
	    public String getZxywh() {
			return zxywh;
		}

		public void setZxywh(String zxywh) {
			this.zxywh = zxywh;
		}
		@Temporal(TemporalType.TIMESTAMP)
	   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
	    @Column(name = "ZXSJ", length = 7)
		public Date getZxsj() {
			return zxsj;
		}

		public void setZxsj(Date zxsj) {
			this.zxsj = zxsj;
		}

		public String getZxdbr() {
			return zxdbr;
		}

		public void setZxdbr(String zxdbr) {
			this.zxdbr = zxdbr;
		}

		private Date zxsj;
	    private String zxdbr;

	    public String getCzfs() {
			return czfs;
		}

		public void setCzfs(String czfs) {
			this.czfs = czfs;
		}

		public Fdcqzxdj_dj() {
	    }

	    public Fdcqzxdj_dj(String bsm) {
		this.bsm = bsm;
	    }


	    @Id
	    @Column(name = "BSM", unique = true, nullable = false, length = 200)
	    public String getBsm() {
		if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
		return this.bsm;
	    }

	    public void setBsm(String bsm) {
		this.bsm = bsm;
	    }

	    @Column(name = "YSDM", length = 100)
	    public String getYsdm() {
		return this.ysdm;
	    }

	    public void setYsdm(String ysdm) {
		this.ysdm = ysdm;
	    }

	    @Column(name = "BDCDYH", length = 100)
	    public String getBdcdyh() {
		return this.bdcdyh;
	    }

	    public void setBdcdyh(String bdcdyh) {
		this.bdcdyh = bdcdyh;
	    }

	    @Column(name = "YWH", length = 100)
	    public String getYwh() {
		return this.ywh;
	    }

	    public void setYwh(String ywh) {
		this.ywh = ywh;
	    }

	    
	    @Column(name = "BDCQZH", length = 4000)
	    public String getBdcqzh() {
		return this.bdcqzh;
	    }

	    public void setBdcqzh(String bdcqzh) {
		this.bdcqzh = bdcqzh;
	    }

	    @Column(name = "QXDM", length = 12)
	    public String getQxdm() {
		return this.qxdm;
	    }

	    public void setQxdm(String qxdm) {
		this.qxdm = qxdm;
	    }

	    @Column(name = "DJJG", length = 400)
	    public String getDjjg() {
		return this.djjg;
	    }

	    public void setDjjg(String djjg) {
		this.djjg = djjg;
	    }

	    @Column(name = "DBR", length = 100)
	    public String getDbr() {
		return this.dbr;
	    }

	    public void setDbr(String dbr) {
		this.dbr = dbr;
	    }

	    @Temporal(TemporalType.TIMESTAMP)
	   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
	    @Column(name = "DJSJ", length = 7)
	    public Date getDjsj() {
		return this.djsj;
	    }

	    public void setDjsj(Date djsj) {
		this.djsj = djsj;
	    }

	    @Column(name = "FJ", length = 2000)
	    public String getFj() {
		return this.fj;
	    }

	    public void setFj(String fj) {
		this.fj = fj;
	    }

	    @Column(name = "QSZT", precision = 38, scale = 0)
	    public BigDecimal getQszt() {
		return this.qszt;
	    }

	    public void setQszt(BigDecimal qszt) {
		this.qszt = qszt;
	    }

	    @Column(name = "QLID", length = 100)
	    public String getQlid() {
		return this.qlid;
	    }

	    public void setQlid(String qlid) {
		this.qlid = qlid;
	    }

	    @Column(name = "BDCDYID", length = 100)
	    public String getBdcdyid() {
		return this.bdcdyid;
	    }

	    public void setBdcdyid(String bdcdyid) {
		this.bdcdyid = bdcdyid;
	    }

	    @Column(name = "GXXMBH", length = 100)
	    public String getGxxmbh() {
		return this.gxxmbh;
	    }

	    public void setGxxmbh(String gxxmbh) {
		this.gxxmbh = gxxmbh;
	    }

	    @Column(name = "ZSBH", length = 40)
	    public String getZsbh() {
		return this.zsbh;
	    }

	    public void setZsbh(String zsbh) {
		this.zsbh = zsbh;
	    }

	    @Column(name = "BZ", length = 4000)
	    public String getBz() {
		return this.bz;
	    }

	    public void setBz(String bz) {
		this.bz = bz;
	    }

	    @Temporal(TemporalType.TIMESTAMP)
	   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
	   	@Column(name = "TSSJ", length = 7)
	   	public Date getTssj() {
	   		return this.tssj;
	   	}

	   	public void setTssj(Date tssj) {
	   		this.tssj = tssj;
	   	}
}
