package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Fdcq generated by hbm2java
 */
@Entity
@Table(name = "FDCQ", schema = "GXDJK")
public class Fdcq_dj implements java.io.Serializable {

    private String bsm;
    private String ysdm;
    private String bdcdyh;
    private String ywh;
    private String qllx;
    private String djlx;
    private String djyy;
    private Date qlqssj;
    private Date qljssj;
    private String bdcqzh;
    private String qxdm;
    private String djjg;
    private String dbr;
    private Date djsj;
    private String fj;
    private BigDecimal qszt;
    private BigDecimal fdcjyjg;
    private String tdshyqr;
    private String fdzl;
    private BigDecimal dytdmj;
    private BigDecimal fttdmj;
    private String ghyt;
    private String fwxz;
    private String fwjg;
    private Integer szc;
    private Integer zcs;
    private BigDecimal jzmj;
    private BigDecimal zyjzmj;
    private BigDecimal ftjzmj;
    private Date jgsj;
    private String qlid;
    private String bdcdyid;
    private String gxxmbh;
    private String zsbh;
    private String bz;
    private String czfs;
    private Date tssj;
    
    public Fdcq_dj() {
    }

    public Fdcq_dj(String bsm) {
	this.bsm = bsm;
    }

    public Fdcq_dj(String bsm, String ysdm, String bdcdyh, String ywh,
	    String qllx, String djlx, String djyy, Date qlqssj, Date qljssj,
	    String bdcqzh, String qxdm, String djjg, String dbr, Date djsj,
	    String fj, BigDecimal qszt, BigDecimal fdcjyjg, String tdshyqr,
	    String fdzl, BigDecimal dytdmj, BigDecimal fttdmj, String ghyt,
	    String fwxz, String fwjg, Integer szc, Integer zcs,
	    BigDecimal jzmj, BigDecimal zyjzmj, BigDecimal ftjzmj, Date jgsj,
	    String qlid, String bdcdyid, String gxxmbh, String zsbh, String bz, String czfs,Date tssj) {
	this.bsm = bsm;
	this.ysdm = ysdm;
	this.bdcdyh = bdcdyh;
	this.ywh = ywh;
	this.qllx = qllx;
	this.djlx = djlx;
	this.djyy = djyy;
	this.qlqssj = qlqssj;
	this.qljssj = qljssj;
	this.bdcqzh = bdcqzh;
	this.qxdm = qxdm;
	this.djjg = djjg;
	this.dbr = dbr;
	this.djsj = djsj;
	this.fj = fj;
	this.qszt = qszt;
	this.fdcjyjg = fdcjyjg;
	this.tdshyqr = tdshyqr;
	this.fdzl = fdzl;
	this.dytdmj = dytdmj;
	this.fttdmj = fttdmj;
	this.ghyt = ghyt;
	this.fwxz = fwxz;
	this.fwjg = fwjg;
	this.szc = szc;
	this.zcs = zcs;
	this.jzmj = jzmj;
	this.zyjzmj = zyjzmj;
	this.ftjzmj = ftjzmj;
	this.jgsj = jgsj;
	this.qlid = qlid;
	this.bdcdyid = bdcdyid;
	this.gxxmbh = gxxmbh;
	this.zsbh = zsbh;
	this.bz = bz;
	this.czfs = czfs;
	this.tssj = tssj;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "YSDM", length = 100)
    public String getYsdm() {
	return this.ysdm;
    }

    public void setYsdm(String ysdm) {
	this.ysdm = ysdm;
    }

    @Column(name = "BDCDYH", length = 100)
    public String getBdcdyh() {
	return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
	this.bdcdyh = bdcdyh;
    }

    @Column(name = "YWH", length = 100)
    public String getYwh() {
	return this.ywh;
    }

    public void setYwh(String ywh) {
	this.ywh = ywh;
    }

    @Column(name = "QLLX", length = 20)
    public String getQllx() {
	return this.qllx;
    }

    public void setQllx(String qllx) {
	this.qllx = qllx;
    }

    @Column(name = "DJLX", length = 20)
    public String getDjlx() {
	return this.djlx;
    }

    public void setDjlx(String djlx) {
	this.djlx = djlx;
    }

    @Column(name = "DJYY", length = 400)
    public String getDjyy() {
	return this.djyy;
    }

    public void setDjyy(String djyy) {
	this.djyy = djyy;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "QLQSSJ", length = 7)
    public Date getQlqssj() {
	return this.qlqssj;
    }

    public void setQlqssj(Date qlqssj) {
	this.qlqssj = qlqssj;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "QLJSSJ", length = 7)
    public Date getQljssj() {
	return this.qljssj;
    }

    public void setQljssj(Date qljssj) {
	this.qljssj = qljssj;
    }

    @Column(name = "BDCQZH", length = 4000)
    public String getBdcqzh() {
	return this.bdcqzh;
    }

    public void setBdcqzh(String bdcqzh) {
	this.bdcqzh = bdcqzh;
    }

    @Column(name = "QXDM", length = 12)
    public String getQxdm() {
	return this.qxdm;
    }

    public void setQxdm(String qxdm) {
	this.qxdm = qxdm;
    }

    @Column(name = "DJJG", length = 400)
    public String getDjjg() {
	return this.djjg;
    }

    public void setDjjg(String djjg) {
	this.djjg = djjg;
    }

    @Column(name = "DBR", length = 100)
    public String getDbr() {
	return this.dbr;
    }

    public void setDbr(String dbr) {
	this.dbr = dbr;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "DJSJ", length = 7)
    public Date getDjsj() {
	return this.djsj;
    }

    public void setDjsj(Date djsj) {
	this.djsj = djsj;
    }

    @Column(name = "FJ", length = 2000)
    public String getFj() {
	return this.fj;
    }

    public void setFj(String fj) {
	this.fj = fj;
    }

    @Column(name = "QSZT", precision = 38, scale = 0)
    public BigDecimal getQszt() {
	return this.qszt;
    }

    public void setQszt(BigDecimal qszt) {
	this.qszt = qszt;
    }

    @Column(name = "FDCJYJG", precision = 38, scale = 16)
    public BigDecimal getFdcjyjg() {
	return this.fdcjyjg;
    }

    public void setFdcjyjg(BigDecimal fdcjyjg) {
	this.fdcjyjg = fdcjyjg;
    }

    @Column(name = "TDSHYQR", length = 200)
    public String getTdshyqr() {
	return this.tdshyqr;
    }

    public void setTdshyqr(String tdshyqr) {
	this.tdshyqr = tdshyqr;
    }

    @Column(name = "FDZL", length = 400)
    public String getFdzl() {
	return this.fdzl;
    }

    public void setFdzl(String fdzl) {
	this.fdzl = fdzl;
    }

    @Column(name = "DYTDMJ", precision = 38, scale = 16)
    public BigDecimal getDytdmj() {
	return this.dytdmj;
    }

    public void setDytdmj(BigDecimal dytdmj) {
	this.dytdmj = dytdmj;
    }

    @Column(name = "FTTDMJ", precision = 38, scale = 16)
    public BigDecimal getFttdmj() {
	return this.fttdmj;
    }

    public void setFttdmj(BigDecimal fttdmj) {
	this.fttdmj = fttdmj;
    }

    @Column(name = "GHYT", length = 4)
    public String getGhyt() {
	return this.ghyt;
    }

    public void setGhyt(String ghyt) {
	this.ghyt = ghyt;
    }

    @Column(name = "FWXZ", length = 4)
    public String getFwxz() {
	return this.fwxz;
    }

    public void setFwxz(String fwxz) {
	this.fwxz = fwxz;
    }

    @Column(name = "FWJG", length = 4)
    public String getFwjg() {
	return this.fwjg;
    }

    public void setFwjg(String fwjg) {
	this.fwjg = fwjg;
    }

    @Column(name = "SZC", precision = 8, scale = 0)
    public Integer getSzc() {
	return this.szc;
    }

    public void setSzc(Integer szc) {
	this.szc = szc;
    }

    @Column(name = "ZCS", precision = 8, scale = 0)
    public Integer getZcs() {
	return this.zcs;
    }

    public void setZcs(Integer zcs) {
	this.zcs = zcs;
    }

    @Column(name = "JZMJ", precision = 38, scale = 16)
    public BigDecimal getJzmj() {
	return this.jzmj;
    }

    public void setJzmj(BigDecimal jzmj) {
	this.jzmj = jzmj;
    }

    @Column(name = "ZYJZMJ", precision = 38, scale = 16)
    public BigDecimal getZyjzmj() {
	return this.zyjzmj;
    }

    public void setZyjzmj(BigDecimal zyjzmj) {
	this.zyjzmj = zyjzmj;
    }

    @Column(name = "FTJZMJ", precision = 38, scale = 16)
    public BigDecimal getFtjzmj() {
	return this.ftjzmj;
    }

    public void setFtjzmj(BigDecimal ftjzmj) {
	this.ftjzmj = ftjzmj;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "JGSJ", length = 7)
    public Date getJgsj() {
	return this.jgsj;
    }

    public void setJgsj(Date jgsj) {
	this.jgsj = jgsj;
    }

    @Column(name = "QLID", length = 100)
    public String getQlid() {
	return this.qlid;
    }

    public void setQlid(String qlid) {
	this.qlid = qlid;
    }

    @Column(name = "BDCDYID", length = 100)
    public String getBdcdyid() {
	return this.bdcdyid;
    }

    public void setBdcdyid(String bdcdyid) {
	this.bdcdyid = bdcdyid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

    @Column(name = "ZSBH", length = 40)
    public String getZsbh() {
	return this.zsbh;
    }

    public void setZsbh(String zsbh) {
	this.zsbh = zsbh;
    }

    @Column(name = "BZ", length = 4000)
    public String getBz() {
	return this.bz;
    }

    public void setBz(String bz) {
	this.bz = bz;
    }

    @Column(name = "CZFS", length = 10)
    public String getCzfs() {
	return this.czfs;
    }

    public void setCzfs(String czfs) {
	this.czfs = czfs;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
   	@Column(name = "TSSJ", length = 7)
   	public Date getTssj() {
   		return this.tssj;
   	}

   	public void setTssj(Date tssj) {
   		this.tssj = tssj;
   	}
}
