package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import oracle.sql.BLOB;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Gxjhxm generated by hbm2java
 */
@Entity
@Table(name = "GXJHXM", schema = "GXDJK")
public class Gxjhxm_dj implements java.io.Serializable {

	private String bsm;
	private String bdcdyh;
	private String qllx;
	private String gxlx;
	private String xmmc;
	private String zl;
	private String gxxmbh;
	private String djdl;
	private String djxl;
	private String sqr;
	private Date slsj;
	private String slry;
	private String zt;
	private String bljd;
	private String casenum;
	private String qlsdfs;
	private String project_id;
	private Date tssj;
	private BigDecimal xmid;
	private Date CQSJ;
	private BigDecimal isdelete;
	private BLOB relationid;
	private String xzqdm;
	private String xzqmc;
	private String ywlsh;

	public Gxjhxm_dj() {
	}

	public Gxjhxm_dj(String bsm, String qllx, String gxxmbh, String djdl) {
		this.bsm = bsm;
		this.qllx = qllx;
		this.gxxmbh = gxxmbh;
		this.djdl = djdl;
	}

	public Gxjhxm_dj(String bsm, String bdcdyh, String qllx, String gxlx,
			String xmmc, String zl, String gxxmbh, String djdl, String djxl,
			String sqr, Date slsj, String slry, String zt, String bljd,
			String casenum, String qlsdfs, String project_id, Date tssj,
			BigDecimal xmid, Date cQSJ, BigDecimal isdelete,BLOB relationid,String xzqdm,String xzqmc,String ywlsh) {
		super();
		this.bsm = bsm;
		this.bdcdyh = bdcdyh;
		this.qllx = qllx;
		this.gxlx = gxlx;
		this.xmmc = xmmc;
		this.zl = zl;
		this.gxxmbh = gxxmbh;
		this.djdl = djdl;
		this.djxl = djxl;
		this.sqr = sqr;
		this.slsj = slsj;
		this.slry = slry;
		this.zt = zt;
		this.bljd = bljd;
		this.casenum = casenum;
		this.qlsdfs = qlsdfs;
		this.project_id = project_id;
		this.tssj = tssj;
		this.xmid = xmid;
		this.CQSJ = cQSJ;
		this.isdelete = isdelete;
		this.relationid = relationid;
		this.xzqdm = xzqdm;
		this.xzqmc = xzqmc;
		this.ywlsh = ywlsh;
	}

	 public Gxjhxm_dj(String bsm, String bdcdyh, String qllx, String gxlx,
	 String xmmc, String zl, String gxxmbh, String djdl, String djxl,
	 String sqr, Date slsj, String slry, String zt, String bljd,
	 String casenum, String qlsdfs, String project_id, Date tssj,
	 BigDecimal xmid) {
	 this.bsm = bsm;
	 this.bdcdyh = bdcdyh;
	 this.qllx = qllx;
	 this.gxlx = gxlx;
	 this.xmmc = xmmc;
	 this.zl = zl;
	 this.gxxmbh = gxxmbh;
	 this.djdl = djdl;
	 this.djxl = djxl;
	 this.sqr = sqr;
	 this.slsj = slsj;
	 this.slry = slry;
	 this.zt = zt;
	 this.bljd = bljd;
	 this.casenum = casenum;
	 this.qlsdfs = qlsdfs;
	 this.project_id = project_id;
	 this.tssj = tssj;
	 this.xmid = xmid;
	 }

	@Id
	@Column(name = "BSM", unique = true, nullable = false, length = 200)
	public String getBsm() {
		if (bsm == null)
			bsm = UUID.randomUUID().toString().replace("-", "");
		return this.bsm;
	}

	public void setBsm(String bsm) {
		this.bsm = bsm;
	}

	@Column(name = "BDCDYH", length = 100)
	public String getBdcdyh() {
		return this.bdcdyh;
	}

	public void setBdcdyh(String bdcdyh) {
		this.bdcdyh = bdcdyh;
	}

	@Column(name = "QLLX", nullable = false, length = 100)
	public String getQllx() {
		return this.qllx;
	}

	public void setQllx(String qllx) {
		this.qllx = qllx;
	}

	@Column(name = "GXLX", length = 100)
	public String getGxlx() {
		return this.gxlx;
	}

	public void setGxlx(String gxlx) {
		this.gxlx = gxlx;
	}

	@Column(name = "XMMC", length = 400)
	public String getXmmc() {
		return this.xmmc;
	}

	public void setXmmc(String xmmc) {
		this.xmmc = xmmc;
	}

	@Column(name = "ZL", length = 400)
	public String getZl() {
		return this.zl;
	}

	public void setZl(String zl) {
		this.zl = zl;
	}

	@Column(name = "GXXMBH", nullable = false, length = 100)
	public String getGxxmbh() {
		return this.gxxmbh;
	}

	public void setGxxmbh(String gxxmbh) {
		this.gxxmbh = gxxmbh;
	}

	@Column(name = "DJDL", nullable = false, length = 20)
	public String getDjdl() {
		return this.djdl;
	}

	public void setDjdl(String djdl) {
		this.djdl = djdl;
	}

	@Column(name = "DJXL", length = 20)
	public String getDjxl() {
		return this.djxl;
	}

	public void setDjxl(String djxl) {
		this.djxl = djxl;
	}

	@Column(name = "SQR", length = 1000)
	public String getSqr() {
		return this.sqr;
	}

	public void setSqr(String sqr) {
		this.sqr = sqr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SLSJ", length = 7)
	public Date getSlsj() {
		return this.slsj;
	}

	public void setSlsj(Date slsj) {
		this.slsj = slsj;
	}

	@Column(name = "SLRY", length = 100)
	public String getSlry() {
		return this.slry;
	}

	public void setSlry(String slry) {
		this.slry = slry;
	}

	@Column(name = "ZT", length = 4)
	public String getZt() {
		return this.zt;
	}

	public void setZt(String zt) {
		this.zt = zt;
	}

	@Column(name = "BLJD", length = 100)
	public String getBljd() {
		return this.bljd;
	}

	public void setBljd(String bljd) {
		this.bljd = bljd;
	}

	@Column(name = "CASENUM", length = 100)
	public String getCasenum() {
		return this.casenum;
	}

	public void setCasenum(String casenum) {
		this.casenum = casenum;
	}

	@Column(name = "QLSDFS", length = 20)
	public String getQlsdfs() {
		return this.qlsdfs;
	}

	public void setQlsdfs(String qlsdfs) {
		this.qlsdfs = qlsdfs;
	}

	@Column(name = "PROJECT_ID", length = 100)
	public String getProject_id() {
		return this.project_id;
	}

	public void setProject_id(String project_id) {
		this.project_id = project_id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
	@Column(name = "TSSJ", length = 7)
	public Date getTssj() {
		return this.tssj;
	}

	public void setTssj(Date tssj) {
		this.tssj = tssj;
	}

	@Column(name = "XMID", precision = 22, scale = 0)
	public BigDecimal getXmid() {
		return this.xmid;
	}

	public void setXmid(BigDecimal xmid) {
		this.xmid = xmid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
	@Column(name = "CQSJ", length = 7)
	public Date getCQSJ() {
		return CQSJ;
	}

	public void setCQSJ(Date cQSJ) {
		CQSJ = cQSJ;
	}

	@Override
	public String toString() {
		return "Gxjhxm_dj [bsm=" + bsm + ", bdcdyh=" + bdcdyh + ", qllx="
				+ qllx + ", gxlx=" + gxlx + ", xmmc=" + xmmc + ", zl=" + zl
				+ ", gxxmbh=" + gxxmbh + ", djdl=" + djdl + ", djxl=" + djxl
				+ ", sqr=" + sqr + ", slsj=" + slsj + ", slry=" + slry
				+ ", zt=" + zt + ", bljd=" + bljd + ", casenum=" + casenum
				+ ", qlsdfs=" + qlsdfs + ", projectId=" + project_id + ", tssj="
				+ tssj + ", xmid=" + xmid + ", CQSJ=" + CQSJ + "]";
	}

	@Column(name = "ISDELETE", precision = 22, scale = 0)
	public BigDecimal getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(BigDecimal isdelete) {
		this.isdelete = isdelete;
	}

	@Column(name = "RELATIONID", length = 2000)
	public BLOB getRelationid() {
		return this.relationid;
	}

	public void setRelationid(BLOB relationid) {
		this.relationid = relationid;
	}

	@Column(name = "XZQDM", length = 100)
	public String getXzqdm() {
		return this.xzqdm;
	}

	public void setXzqdm(String xzqdm) {
		this.xzqdm = xzqdm;
	}
	@Column(name = "XZQMC", length = 200)
	public String getXzqmc() {
		return this.xzqmc;
	}

	public void setXzqmc(String xzqmc) {
		this.xzqmc = xzqmc;
	}
	@Column(name = "YWLSH", length = 200)
	public String getYwlsh() {
		return this.ywlsh;
	}

	public void setYwlsh(String ywlsh) {
		this.ywlsh = ywlsh;
	}
}
