package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ht generated by hbm2java
 */
@Entity
@Table(name = "HT", schema = "GXDJK")
public class Ht_dj implements java.io.Serializable {

    private String bsm;
    private String gxxmbh;
    private String htbh;
    private Date qdsj;
    private Date basj;
    private BigDecimal jyje;
    private Blob fj;

    public Ht_dj() {
    }

    public Ht_dj(String bsm) {
	this.bsm = bsm;
    }

    public Ht_dj(String bsm, String gxxmbh, String htbh, Date qdsj, Date basj,
	    BigDecimal jyje, Blob fj) {
	this.bsm = bsm;
	this.gxxmbh = gxxmbh;
	this.htbh = htbh;
	this.qdsj = qdsj;
	this.basj = basj;
	this.jyje = jyje;
	this.fj = fj;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "GXXMBH", length = 200)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

    @Column(name = "HTBH", length = 200)
    public String getHtbh() {
	return this.htbh;
    }

    public void setHtbh(String htbh) {
	this.htbh = htbh;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "QDSJ", length = 7)
    public Date getQdsj() {
	return this.qdsj;
    }

    public void setQdsj(Date qdsj) {
	this.qdsj = qdsj;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "BASJ", length = 7)
    public Date getBasj() {
	return this.basj;
    }

    public void setBasj(Date basj) {
	this.basj = basj;
    }

    @Column(name = "JYJE", precision = 38, scale = 8)
    public BigDecimal getJyje() {
	return this.jyje;
    }

    public void setJyje(BigDecimal jyje) {
	this.jyje = jyje;
    }

    @Column(name = "FJ")
    public Blob getFj() {
	return this.fj;
    }

    public void setFj(Blob fj) {
	this.fj = fj;
    }

}
