package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jsydsyq generated by hbm2java
 */
@Entity
@Table(name = "JSYDSYQ", schema = "GXDJK")
public class Jsydsyq_dj implements java.io.Serializable {

    private String bsm;
    private String ysdm;
    private String bdcdyh;
    private String ywh;
    private String qllx;
    private String djlx;
    private String djyy;
    private Date syqqssj;
    private Date syqjssj;
    private String bdcqzh;
    private String qxdm;
    private String djjg;
    private String dbr;
    private Date djsj;
    private String fj;
    private BigDecimal qszt;
    private BigDecimal qdjg;
    private String qlid;
    private String bdcdyid;
    private String gxxmbh;
    private String zsbh;
    private String bz;
    private String zddm;
    private BigDecimal syqmj;
    private String gxlx;

    public Jsydsyq_dj() {
    }

    public Jsydsyq_dj(String bsm) {
	this.bsm = bsm;
    }

    public Jsydsyq_dj(String bsm, String ysdm, String bdcdyh, String ywh,
	    String qllx, String djlx, String djyy, Date syqqssj, Date syqjssj,
	    String bdcqzh, String qxdm, String djjg, String dbr, Date djsj,
	    String fj, BigDecimal qszt, BigDecimal qdjg, String qlid,
	    String bdcdyid, String gxxmbh, String zsbh, String bz, String zddm,
	    BigDecimal syqmj, String gxlx) {
	this.bsm = bsm;
	this.ysdm = ysdm;
	this.bdcdyh = bdcdyh;
	this.ywh = ywh;
	this.qllx = qllx;
	this.djlx = djlx;
	this.djyy = djyy;
	this.syqqssj = syqqssj;
	this.syqjssj = syqjssj;
	this.bdcqzh = bdcqzh;
	this.qxdm = qxdm;
	this.djjg = djjg;
	this.dbr = dbr;
	this.djsj = djsj;
	this.fj = fj;
	this.qszt = qszt;
	this.qdjg = qdjg;
	this.qlid = qlid;
	this.bdcdyid = bdcdyid;
	this.gxxmbh = gxxmbh;
	this.zsbh = zsbh;
	this.bz = bz;
	this.zddm = zddm;
	this.syqmj = syqmj;
	this.gxlx = gxlx;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "YSDM", length = 100)
    public String getYsdm() {
	return this.ysdm;
    }

    public void setYsdm(String ysdm) {
	this.ysdm = ysdm;
    }

    @Column(name = "BDCDYH", length = 100)
    public String getBdcdyh() {
	return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
	this.bdcdyh = bdcdyh;
    }

    @Column(name = "YWH", length = 100)
    public String getYwh() {
	return this.ywh;
    }

    public void setYwh(String ywh) {
	this.ywh = ywh;
    }

    @Column(name = "QLLX", length = 20)
    public String getQllx() {
	return this.qllx;
    }

    public void setQllx(String qllx) {
	this.qllx = qllx;
    }

    @Column(name = "DJLX", length = 20)
    public String getDjlx() {
	return this.djlx;
    }

    public void setDjlx(String djlx) {
	this.djlx = djlx;
    }

    @Column(name = "DJYY", length = 400)
    public String getDjyy() {
	return this.djyy;
    }

    public void setDjyy(String djyy) {
	this.djyy = djyy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "SYQQSSJ", length = 7)
    public Date getSyqqssj() {
	return this.syqqssj;
    }

    public void setSyqqssj(Date syqqssj) {
	this.syqqssj = syqqssj;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "SYQJSSJ", length = 7)
    public Date getSyqjssj() {
	return this.syqjssj;
    }

    public void setSyqjssj(Date syqjssj) {
	this.syqjssj = syqjssj;
    }

    @Column(name = "BDCQZH", length = 4000)
    public String getBdcqzh() {
	return this.bdcqzh;
    }

    public void setBdcqzh(String bdcqzh) {
	this.bdcqzh = bdcqzh;
    }

    @Column(name = "QXDM", length = 12)
    public String getQxdm() {
	return this.qxdm;
    }

    public void setQxdm(String qxdm) {
	this.qxdm = qxdm;
    }

    @Column(name = "DJJG", length = 400)
    public String getDjjg() {
	return this.djjg;
    }

    public void setDjjg(String djjg) {
	this.djjg = djjg;
    }

    @Column(name = "DBR", length = 100)
    public String getDbr() {
	return this.dbr;
    }

    public void setDbr(String dbr) {
	this.dbr = dbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DJSJ", length = 7)
    public Date getDjsj() {
	return this.djsj;
    }

    public void setDjsj(Date djsj) {
	this.djsj = djsj;
    }

    @Column(name = "FJ", length = 2000)
    public String getFj() {
	return this.fj;
    }

    public void setFj(String fj) {
	this.fj = fj;
    }

    @Column(name = "QSZT", precision = 38, scale = 0)
    public BigDecimal getQszt() {
	return this.qszt;
    }

    public void setQszt(BigDecimal qszt) {
	this.qszt = qszt;
    }

    @Column(name = "QDJG", precision = 38, scale = 16)
    public BigDecimal getQdjg() {
	return this.qdjg;
    }

    public void setQdjg(BigDecimal qdjg) {
	this.qdjg = qdjg;
    }

    @Column(name = "QLID", length = 100)
    public String getQlid() {
	return this.qlid;
    }

    public void setQlid(String qlid) {
	this.qlid = qlid;
    }

    @Column(name = "BDCDYID", length = 100)
    public String getBdcdyid() {
	return this.bdcdyid;
    }

    public void setBdcdyid(String bdcdyid) {
	this.bdcdyid = bdcdyid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

    @Column(name = "ZSBH", length = 40)
    public String getZsbh() {
	return this.zsbh;
    }

    public void setZsbh(String zsbh) {
	this.zsbh = zsbh;
    }

    @Column(name = "BZ", length = 4000)
    public String getBz() {
	return this.bz;
    }

    public void setBz(String bz) {
	this.bz = bz;
    }

    @Column(name = "ZDDM", length = 38)
    public String getZddm() {
	return this.zddm;
    }

    public void setZddm(String zddm) {
	this.zddm = zddm;
    }

    @Column(name = "SYQMJ", precision = 38, scale = 16)
    public BigDecimal getSyqmj() {
	return this.syqmj;
    }

    public void setSyqmj(BigDecimal syqmj) {
	this.syqmj = syqmj;
    }

    @Column(name = "GXLX", length = 4)
    public String getGxlx() {
	return this.gxlx;
    }

    public void setGxlx(String gxlx) {
	this.gxlx = gxlx;
    }

}
