package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Gxjhxm generated by hbm2java
 */
@Entity
@Table(name = "LOG", schema = "GXDJK")
public class Log_dj implements java.io.Serializable {

	private String bsm;
	private String bdcdyh;
	private String gxxmbh;
	private String bljd;
	private String project_id;
	private Date tssj;
	private String ywlsh;
	private String djdl;
	private String qllx;
	
	public Log_dj() {
	}


	public Log_dj(String bsm, String bdcdyh, String gxxmbh,String bljd, String project_id, Date tssj,String ywlsh) {
		super();
		this.bsm = bsm;
		this.bdcdyh = bdcdyh;
		this.gxxmbh = gxxmbh;
		this.bljd = bljd;
		this.project_id = project_id;
		this.tssj = tssj;
		this.ywlsh = ywlsh;
	}

	 public Log_dj(String bsm, String bdcdyh, String gxxmbh, String bljd,String project_id, Date tssj) {
	 this.bsm = bsm;
	 this.bdcdyh = bdcdyh;
	 this.gxxmbh = gxxmbh;
	 this.bljd = bljd;
	 this.project_id = project_id;
	 this.tssj = tssj;
	 }

	@Id
	@Column(name = "BSM", unique = true, nullable = false, length = 200)
	public String getBsm() {
		if (bsm == null)
			bsm = UUID.randomUUID().toString().replace("-", "");
		return this.bsm;
	}

	public void setBsm(String bsm) {
		this.bsm = bsm;
	}

	@Column(name = "BDCDYH", length = 100)
	public String getBdcdyh() {
		return this.bdcdyh;
	}

	public void setBdcdyh(String bdcdyh) {
		this.bdcdyh = bdcdyh;
	}

	@Column(name = "GXXMBH", nullable = false, length = 100)
	public String getGxxmbh() {
		return this.gxxmbh;
	}

	public void setGxxmbh(String gxxmbh) {
		this.gxxmbh = gxxmbh;
	}
	
	@Column(name = "BLJD", length = 100)
	public String getBljd() {
		return this.bljd;
	}

	public void setBljd(String bljd) {
		this.bljd = bljd;
	}

	@Column(name = "PROJECT_ID", length = 100)
	public String getProject_id() {
		return this.project_id;
	}

	public void setProject_id(String project_id) {
		this.project_id = project_id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
	@Column(name = "TSSJ", length = 7)
	public Date getTssj() {
		return this.tssj;
	}

	public void setTssj(Date tssj) {
		this.tssj = tssj;
	}

	@Column(name = "YWLSH", length = 200)
	public String getYwlsh() {
		return this.ywlsh;
	}

	public void setYwlsh(String ywlsh) {
		this.ywlsh = ywlsh;
	}
	
	@Column(name = "DJDL", length = 200)
	public String getDjdl() {
		return this.djdl;
	}

	public void setDjdl(String djdl) {
		this.djdl = djdl;
	}
	
	@Column(name = "QLLX", length = 200)
	public String getQllx() {
		return this.qllx;
	}

	public void setQllx(String qllx) {
		this.qllx = qllx;
	}
	
}
