package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tdyt generated by hbm2java
 */
@Entity
@Table(name = "TDYT", schema = "GXDJK")
public class Tdyt_dj implements java.io.Serializable {

    private String bsm;
    private String bdcdyid;
    private String gxxmbh;
    private String bz;
    private String relationid;
    private String gxlx;
    private String tdyt;
    private String tdytmc;
    private String sfzyt;
    private String tddj;
    private BigDecimal tdjg;
    private Date qlqsrq;
    private Date qlzzrq;
    private BigDecimal syqx;
    private BigDecimal crjbz;

    public Tdyt_dj() {
    }

    public Tdyt_dj(String bsm) {
	this.bsm = bsm;
    }

    public Tdyt_dj(String bsm, String bdcdyid, String gxxmbh, String bz,
	    String relationid, String gxlx, String tdyt, String tdytmc,
	    String sfzyt, String tddj, BigDecimal tdjg, Date qlqsrq,
	    Date qlzzrq, BigDecimal syqx, BigDecimal crjbz) {
	this.bsm = bsm;
	this.bdcdyid = bdcdyid;
	this.gxxmbh = gxxmbh;
	this.bz = bz;
	this.relationid = relationid;
	this.gxlx = gxlx;
	this.tdyt = tdyt;
	this.tdytmc = tdytmc;
	this.sfzyt = sfzyt;
	this.tddj = tddj;
	this.tdjg = tdjg;
	this.qlqsrq = qlqsrq;
	this.qlzzrq = qlzzrq;
	this.syqx = syqx;
	this.crjbz = crjbz;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "BDCDYID", length = 100)
    public String getBdcdyid() {
	return this.bdcdyid;
    }

    public void setBdcdyid(String bdcdyid) {
	this.bdcdyid = bdcdyid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

    @Column(name = "BZ", length = 4000)
    public String getBz() {
	return this.bz;
    }

    public void setBz(String bz) {
	this.bz = bz;
    }

    @Column(name = "RELATIONID", length = 400)
    public String getRelationid() {
	return this.relationid;
    }

    public void setRelationid(String relationid) {
	this.relationid = relationid;
    }

    @Column(name = "GXLX", length = 4)
    public String getGxlx() {
	return this.gxlx;
    }

    public void setGxlx(String gxlx) {
	this.gxlx = gxlx;
    }

    @Column(name = "TDYT", length = 20)
    public String getTdyt() {
	return this.tdyt;
    }

    public void setTdyt(String tdyt) {
	this.tdyt = tdyt;
    }

    @Column(name = "TDYTMC", length = 200)
    public String getTdytmc() {
	return this.tdytmc;
    }

    public void setTdytmc(String tdytmc) {
	this.tdytmc = tdytmc;
    }

    @Column(name = "SFZYT", length = 4)
    public String getSfzyt() {
	return this.sfzyt;
    }

    public void setSfzyt(String sfzyt) {
	this.sfzyt = sfzyt;
    }

    @Column(name = "TDDJ", length = 20)
    public String getTddj() {
	return this.tddj;
    }

    public void setTddj(String tddj) {
	this.tddj = tddj;
    }

    @Column(name = "TDJG", precision = 38, scale = 8)
    public BigDecimal getTdjg() {
	return this.tdjg;
    }

    public void setTdjg(BigDecimal tdjg) {
	this.tdjg = tdjg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "QLQSRQ", length = 7)
    public Date getQlqsrq() {
	return this.qlqsrq;
    }

    public void setQlqsrq(Date qlqsrq) {
	this.qlqsrq = qlqsrq;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "QLZZRQ", length = 7)
    public Date getQlzzrq() {
	return this.qlzzrq;
    }

    public void setQlzzrq(Date qlzzrq) {
	this.qlzzrq = qlzzrq;
    }

    @Column(name = "SYQX", precision = 22, scale = 0)
    public BigDecimal getSyqx() {
	return this.syqx;
    }

    public void setSyqx(BigDecimal syqx) {
	this.syqx = syqx;
    }

    @Column(name = "CRJBZ", precision = 38, scale = 8)
    public BigDecimal getCrjbz() {
	return this.crjbz;
    }

    public void setCrjbz(BigDecimal crjbz) {
	this.crjbz = crjbz;
    }

}
