package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Ygdj generated by hbm2java
 */
@Entity
@Table(name = "YGDJ", schema = "GXDJK")
public class Ygdj_dj implements java.io.Serializable {

    private String bsm;
    private String ysdm;
    private String ywh;
    private String bdcdyh;
    private String qlid;
    private String djlx;
    private String djyy;
    private String bdcdjzmh;
    private String qxdm;
    private String djjg;
    private String dbr;
    private Date djsj;
    private String fj;
    private String qszt;
    private String bdcdyid;
    private String gxxmbh;
    private String bdczl;
    private String ywr;
    private String ywrzjzl;
    private String ywrzjh;
    private String ygdjzl;
    private String tdsyqr;
    private String ghyt;
    private String fwxz;
    private String fwjg;
    private Integer szc;
    private Integer zcs;
    private BigDecimal jzmj;
    private BigDecimal qdjg;
    private String zsbh;
    private String bz;
    private Date tssj;
    
    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "ZXSJ", length = 7)
    public Date getZxsj() {
		return zxsj;
	}

	public void setZxsj(Date zxsj) {
		this.zxsj = zxsj;
	}

	public String getZxdbr() {
		return zxdbr;
	}

	public void setZxdbr(String zxdbr) {
		this.zxdbr = zxdbr;
	}

	private Date zxsj;
    private String zxdbr;
    public Ygdj_dj() {
    }

    public Ygdj_dj(String bsm) {
	this.bsm = bsm;
    }

    public Ygdj_dj(String bsm, String ysdm, String ywh, String bdcdyh,
	    String qlid, String djlx, String djyy, String bdcdjzmh,
	    String qxdm, String djjg, String dbr, Date djsj, String fj,
	    String qszt, String bdcdyid, String gxxmbh, String bdczl,
	    String ywr, String ywrzjzl, String ywrzjh, String ygdjzl,
	    String tdsyqr, String ghyt, String fwxz, String fwjg, Integer szc,
	    Integer zcs, BigDecimal jzmj, BigDecimal qdjg, String zsbh,
	    String bz,Date tssj) {
	this.bsm = bsm;
	this.ysdm = ysdm;
	this.ywh = ywh;
	this.bdcdyh = bdcdyh;
	this.qlid = qlid;
	this.djlx = djlx;
	this.djyy = djyy;
	this.bdcdjzmh = bdcdjzmh;
	this.qxdm = qxdm;
	this.djjg = djjg;
	this.dbr = dbr;
	this.djsj = djsj;
	this.fj = fj;
	this.qszt = qszt;
	this.bdcdyid = bdcdyid;
	this.gxxmbh = gxxmbh;
	this.bdczl = bdczl;
	this.ywr = ywr;
	this.ywrzjzl = ywrzjzl;
	this.ywrzjh = ywrzjh;
	this.ygdjzl = ygdjzl;
	this.tdsyqr = tdsyqr;
	this.ghyt = ghyt;
	this.fwxz = fwxz;
	this.fwjg = fwjg;
	this.szc = szc;
	this.zcs = zcs;
	this.jzmj = jzmj;
	this.qdjg = qdjg;
	this.zsbh = zsbh;
	this.bz = bz;
	this.tssj = tssj;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "YSDM", length = 100)
    public String getYsdm() {
	return this.ysdm;
    }

    public void setYsdm(String ysdm) {
	this.ysdm = ysdm;
    }

    @Column(name = "YWH", length = 100)
    public String getYwh() {
	return this.ywh;
    }

    public void setYwh(String ywh) {
	this.ywh = ywh;
    }

    @Column(name = "BDCDYH", length = 100)
    public String getBdcdyh() {
	return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
	this.bdcdyh = bdcdyh;
    }

    @Column(name = "QLID", length = 100)
    public String getQlid() {
	return this.qlid;
    }

    public void setQlid(String qlid) {
	this.qlid = qlid;
    }

    @Column(name = "DJLX", length = 12)
    public String getDjlx() {
	return this.djlx;
    }

    public void setDjlx(String djlx) {
	this.djlx = djlx;
    }

    @Column(name = "DJYY", length = 100)
    public String getDjyy() {
	return this.djyy;
    }

    public void setDjyy(String djyy) {
	this.djyy = djyy;
    }

    @Column(name = "BDCDJZMH", length = 100)
    public String getBdcdjzmh() {
	return this.bdcdjzmh;
    }

    public void setBdcdjzmh(String bdcdjzmh) {
	this.bdcdjzmh = bdcdjzmh;
    }

    @Column(name = "QXDM", length = 12)
    public String getQxdm() {
	return this.qxdm;
    }

    public void setQxdm(String qxdm) {
	this.qxdm = qxdm;
    }

    @Column(name = "DJJG", length = 400)
    public String getDjjg() {
	return this.djjg;
    }

    public void setDjjg(String djjg) {
	this.djjg = djjg;
    }

    @Column(name = "DBR", length = 40)
    public String getDbr() {
	return this.dbr;
    }

    public void setDbr(String dbr) {
	this.dbr = dbr;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "DJSJ", length = 7)
    public Date getDjsj() {
	return this.djsj;
    }

    public void setDjsj(Date djsj) {
	this.djsj = djsj;
    }

    @Column(name = "FJ", length = 4000)
    public String getFj() {
	return this.fj;
    }

    public void setFj(String fj) {
	this.fj = fj;
    }

    @Column(name = "QSZT", length = 4)
    public String getQszt() {
	return this.qszt;
    }

    public void setQszt(String qszt) {
	this.qszt = qszt;
    }

    @Column(name = "BDCDYID", length = 100)
    public String getBdcdyid() {
	return this.bdcdyid;
    }

    public void setBdcdyid(String bdcdyid) {
	this.bdcdyid = bdcdyid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

    @Column(name = "BDCZL", length = 400)
    public String getBdczl() {
	return this.bdczl;
    }

    public void setBdczl(String bdczl) {
	this.bdczl = bdczl;
    }

    @Column(name = "YWR", length = 100)
    public String getYwr() {
	return this.ywr;
    }

    public void setYwr(String ywr) {
	this.ywr = ywr;
    }

    @Column(name = "YWRZJZL", length = 4)
    public String getYwrzjzl() {
	return this.ywrzjzl;
    }

    public void setYwrzjzl(String ywrzjzl) {
	this.ywrzjzl = ywrzjzl;
    }

    @Column(name = "YWRZJH", length = 100)
    public String getYwrzjh() {
	return this.ywrzjh;
    }

    public void setYwrzjh(String ywrzjh) {
	this.ywrzjh = ywrzjh;
    }

    @Column(name = "YGDJZL", length = 4)
    public String getYgdjzl() {
	return this.ygdjzl;
    }

    public void setYgdjzl(String ygdjzl) {
	this.ygdjzl = ygdjzl;
    }

    @Column(name = "TDSYQR", length = 100)
    public String getTdsyqr() {
	return this.tdsyqr;
    }

    public void setTdsyqr(String tdsyqr) {
	this.tdsyqr = tdsyqr;
    }

    @Column(name = "GHYT", length = 4)
    public String getGhyt() {
	return this.ghyt;
    }

    public void setGhyt(String ghyt) {
	this.ghyt = ghyt;
    }

    @Column(name = "FWXZ", length = 4)
    public String getFwxz() {
	return this.fwxz;
    }

    public void setFwxz(String fwxz) {
	this.fwxz = fwxz;
    }

    @Column(name = "FWJG", length = 4)
    public String getFwjg() {
	return this.fwjg;
    }

    public void setFwjg(String fwjg) {
	this.fwjg = fwjg;
    }

    @Column(name = "SZC", precision = 8, scale = 0)
    public Integer getSzc() {
	return this.szc;
    }

    public void setSzc(Integer szc) {
	this.szc = szc;
    }

    @Column(name = "ZCS", precision = 8, scale = 0)
    public Integer getZcs() {
	return this.zcs;
    }

    public void setZcs(Integer zcs) {
	this.zcs = zcs;
    }

    @Column(name = "JZMJ", precision = 38, scale = 16)
    public BigDecimal getJzmj() {
	return this.jzmj;
    }

    public void setJzmj(BigDecimal jzmj) {
	this.jzmj = jzmj;
    }

    @Column(name = "QDJG", precision = 38, scale = 16)
    public BigDecimal getQdjg() {
	return this.qdjg;
    }

    public void setQdjg(BigDecimal qdjg) {
	this.qdjg = qdjg;
    }

    @Column(name = "ZSBH", length = 40)
    public String getZsbh() {
	return this.zsbh;
    }

    public void setZsbh(String zsbh) {
	this.zsbh = zsbh;
    }

    @Column(name = "BZ", length = 4000)
    public String getBz() {
	return this.bz;
    }

    public void setBz(String bz) {
	this.bz = bz;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
   	@Column(name = "TSSJ", length = 7)
   	public Date getTssj() {
   		return this.tssj;
   	}

   	public void setTssj(Date tssj) {
   		this.tssj = tssj;
   	}
}
