package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Yydj generated by hbm2java
 */
@Entity
@Table(name = "YYDJ", schema = "GXDJK", uniqueConstraints = @UniqueConstraint(columnNames = "YSDM"))
public class Yydj_dj implements java.io.Serializable {

    private String bsm;
    private String ysdm;
    private String ywh;
    private String bdcdyh;
    private String qlid;
    private String yysx;
    private String bdcdjzmh;
    private String qxdm;
    private String djjg;
    private String dbr;
    private Date djsj;
    private String fj;
    private String qszt;
    private String bdcdyid;
    private String gxxmbh;
    private String zxyyyy;
    private String zxyydbr;
    private Date zxyydjsj;
    private String zxyyywh;
    private String zsbh;
    private String bz;
    private Date tssj;

    public Yydj_dj() {
    }

    public Yydj_dj(String bsm) {
	this.bsm = bsm;
    }

    public Yydj_dj(String bsm, String ysdm, String ywh, String bdcdyh,
	    String qlid, String yysx, String bdcdjzmh, String qxdm,
	    String djjg, String dbr, Date djsj, String fj, String qszt,
	    String bdcdyid, String gxxmbh, String zxyyyy, String zxyydbr,
	    Date zxyydjsj, String zxyyywh, String zsbh, String bz,Date tssj) {
	this.bsm = bsm;
	this.ysdm = ysdm;
	this.ywh = ywh;
	this.bdcdyh = bdcdyh;
	this.qlid = qlid;
	this.yysx = yysx;
	this.bdcdjzmh = bdcdjzmh;
	this.qxdm = qxdm;
	this.djjg = djjg;
	this.dbr = dbr;
	this.djsj = djsj;
	this.fj = fj;
	this.qszt = qszt;
	this.bdcdyid = bdcdyid;
	this.gxxmbh = gxxmbh;
	this.zxyyyy = zxyyyy;
	this.zxyydbr = zxyydbr;
	this.zxyydjsj = zxyydjsj;
	this.zxyyywh = zxyyywh;
	this.zsbh = zsbh;
	this.bz = bz;
	this.tssj = tssj;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "YSDM", unique = true, length = 100)
    public String getYsdm() {
	return this.ysdm;
    }

    public void setYsdm(String ysdm) {
	this.ysdm = ysdm;
    }

    @Column(name = "YWH", length = 100)
    public String getYwh() {
	return this.ywh;
    }

    public void setYwh(String ywh) {
	this.ywh = ywh;
    }

    @Column(name = "BDCDYH", length = 100)
    public String getBdcdyh() {
	return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
	this.bdcdyh = bdcdyh;
    }

    @Column(name = "QLID", length = 100)
    public String getQlid() {
	return this.qlid;
    }

    public void setQlid(String qlid) {
	this.qlid = qlid;
    }

    @Column(name = "YYSX", length = 4000)
    public String getYysx() {
	return this.yysx;
    }

    public void setYysx(String yysx) {
	this.yysx = yysx;
    }

    @Column(name = "BDCDJZMH", length = 100)
    public String getBdcdjzmh() {
	return this.bdcdjzmh;
    }

    public void setBdcdjzmh(String bdcdjzmh) {
	this.bdcdjzmh = bdcdjzmh;
    }

    @Column(name = "QXDM", length = 12)
    public String getQxdm() {
	return this.qxdm;
    }

    public void setQxdm(String qxdm) {
	this.qxdm = qxdm;
    }

    @Column(name = "DJJG", length = 400)
    public String getDjjg() {
	return this.djjg;
    }

    public void setDjjg(String djjg) {
	this.djjg = djjg;
    }

    @Column(name = "DBR", length = 40)
    public String getDbr() {
	return this.dbr;
    }

    public void setDbr(String dbr) {
	this.dbr = dbr;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "DJSJ", length = 7)
    public Date getDjsj() {
	return this.djsj;
    }

    public void setDjsj(Date djsj) {
	this.djsj = djsj;
    }

    @Column(name = "FJ", length = 4000)
    public String getFj() {
	return this.fj;
    }

    public void setFj(String fj) {
	this.fj = fj;
    }

    @Column(name = "QSZT", length = 4)
    public String getQszt() {
	return this.qszt;
    }

    public void setQszt(String qszt) {
	this.qszt = qszt;
    }

    @Column(name = "BDCDYID", length = 100)
    public String getBdcdyid() {
	return this.bdcdyid;
    }

    public void setBdcdyid(String bdcdyid) {
	this.bdcdyid = bdcdyid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

    @Column(name = "ZXYYYY", length = 1000)
    public String getZxyyyy() {
	return this.zxyyyy;
    }

    public void setZxyyyy(String zxyyyy) {
	this.zxyyyy = zxyyyy;
    }

    @Column(name = "ZXYYDBR", length = 100)
    public String getZxyydbr() {
	return this.zxyydbr;
    }

    public void setZxyydbr(String zxyydbr) {
	this.zxyydbr = zxyydbr;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "ZXYYDJSJ", length = 7)
    public Date getZxyydjsj() {
	return this.zxyydjsj;
    }

    public void setZxyydjsj(Date zxyydjsj) {
	this.zxyydjsj = zxyydjsj;
    }

    @Column(name = "ZXYYYWH", length = 4)
    public String getZxyyywh() {
	return this.zxyyywh;
    }

    public void setZxyyywh(String zxyyywh) {
	this.zxyyywh = zxyyywh;
    }

    @Column(name = "ZSBH", length = 40)
    public String getZsbh() {
	return this.zsbh;
    }

    public void setZsbh(String zsbh) {
	this.zsbh = zsbh;
    }

    @Column(name = "BZ", length = 4000)
    public String getBz() {
	return this.bz;
    }

    public void setBz(String bz) {
	this.bz = bz;
    }

    @Temporal(TemporalType.TIMESTAMP)
   	@DateTimeFormat(style = "yyyy-MM-dd HH:mm:ss")
   	@Column(name = "TSSJ", length = 7)
   	public Date getTssj() {
   		return this.tssj;
   	}

   	public void setTssj(Date tssj) {
   		this.tssj = tssj;
   	}
}
