package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Zd generated by hbm2java
 */
@Entity
@Table(name = "ZD", schema = "GXDJK")
public class Zd_dj implements java.io.Serializable {

    private String bsm;
    private String ysdm;
    private String bdcdyh;
    private String qllx;
    private String bdcdyid;
    private String gxxmbh;
    private String bz;
    private String zddm;
    private String zdtzm;
    private String zl;
    private BigDecimal zdmj;
    private String mjdw;
    private String yt;
    private String dj;
    private BigDecimal jg;
    private String qlxz;
    private String qlsdfs;
    private BigDecimal rjl;
    private BigDecimal jzmd;
    private BigDecimal jzxg;
    private String zdszd;
    private String zdszn;
    private String zdszx;
    private String zdszb;
    private String zdt;
    private String tfh;
    private String djh;
    private String zt;
    private String relationid;
    private String gxlx;

    public Zd_dj() {
    }

    public Zd_dj(String bsm) {
	this.bsm = bsm;
    }

    public Zd_dj(String bsm, String ysdm, String bdcdyh, String qllx,
	    String bdcdyid, String gxxmbh, String bz, String zddm,
	    String zdtzm, String zl, BigDecimal zdmj, String mjdw, String yt,
	    String dj, BigDecimal jg, String qlxz, String qlsdfs,
	    BigDecimal rjl, BigDecimal jzmd, BigDecimal jzxg, String zdszd,
	    String zdszn, String zdszx, String zdszb, String zdt, String tfh,
	    String djh, String zt, String relationid, String gxlx) {
	this.bsm = bsm;
	this.ysdm = ysdm;
	this.bdcdyh = bdcdyh;
	this.qllx = qllx;
	this.bdcdyid = bdcdyid;
	this.gxxmbh = gxxmbh;
	this.bz = bz;
	this.zddm = zddm;
	this.zdtzm = zdtzm;
	this.zl = zl;
	this.zdmj = zdmj;
	this.mjdw = mjdw;
	this.yt = yt;
	this.dj = dj;
	this.jg = jg;
	this.qlxz = qlxz;
	this.qlsdfs = qlsdfs;
	this.rjl = rjl;
	this.jzmd = jzmd;
	this.jzxg = jzxg;
	this.zdszd = zdszd;
	this.zdszn = zdszn;
	this.zdszx = zdszx;
	this.zdszb = zdszb;
	this.zdt = zdt;
	this.tfh = tfh;
	this.djh = djh;
	this.zt = zt;
	this.relationid = relationid;
	this.gxlx = gxlx;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "YSDM", length = 100)
    public String getYsdm() {
	return this.ysdm;
    }

    public void setYsdm(String ysdm) {
	this.ysdm = ysdm;
    }

    @Column(name = "BDCDYH", length = 100)
    public String getBdcdyh() {
	return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
	this.bdcdyh = bdcdyh;
    }

    @Column(name = "QLLX", length = 20)
    public String getQllx() {
	return this.qllx;
    }

    public void setQllx(String qllx) {
	this.qllx = qllx;
    }

    @Column(name = "BDCDYID", length = 100)
    public String getBdcdyid() {
	return this.bdcdyid;
    }

    public void setBdcdyid(String bdcdyid) {
	this.bdcdyid = bdcdyid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

    @Column(name = "BZ", length = 4000)
    public String getBz() {
	return this.bz;
    }

    public void setBz(String bz) {
	this.bz = bz;
    }

    @Column(name = "ZDDM", length = 38)
    public String getZddm() {
	return this.zddm;
    }

    public void setZddm(String zddm) {
	this.zddm = zddm;
    }

    @Column(name = "ZDTZM", length = 4)
    public String getZdtzm() {
	return this.zdtzm;
    }

    public void setZdtzm(String zdtzm) {
	this.zdtzm = zdtzm;
    }

    @Column(name = "ZL", length = 400)
    public String getZl() {
	return this.zl;
    }

    public void setZl(String zl) {
	this.zl = zl;
    }

    @Column(name = "ZDMJ", precision = 38, scale = 16)
    public BigDecimal getZdmj() {
	return this.zdmj;
    }

    public void setZdmj(BigDecimal zdmj) {
	this.zdmj = zdmj;
    }

    @Column(name = "MJDW", length = 20)
    public String getMjdw() {
	return this.mjdw;
    }

    public void setMjdw(String mjdw) {
	this.mjdw = mjdw;
    }

    @Column(name = "YT", length = 8)
    public String getYt() {
	return this.yt;
    }

    public void setYt(String yt) {
	this.yt = yt;
    }

    @Column(name = "DJ", length = 4)
    public String getDj() {
	return this.dj;
    }

    public void setDj(String dj) {
	this.dj = dj;
    }

    @Column(name = "JG", precision = 38, scale = 16)
    public BigDecimal getJg() {
	return this.jg;
    }

    public void setJg(BigDecimal jg) {
	this.jg = jg;
    }

    @Column(name = "QLXZ", length = 8)
    public String getQlxz() {
	return this.qlxz;
    }

    public void setQlxz(String qlxz) {
	this.qlxz = qlxz;
    }

    @Column(name = "QLSDFS", length = 4)
    public String getQlsdfs() {
	return this.qlsdfs;
    }

    public void setQlsdfs(String qlsdfs) {
	this.qlsdfs = qlsdfs;
    }

    @Column(name = "RJL", precision = 38, scale = 16)
    public BigDecimal getRjl() {
	return this.rjl;
    }

    public void setRjl(BigDecimal rjl) {
	this.rjl = rjl;
    }

    @Column(name = "JZMD", precision = 38, scale = 16)
    public BigDecimal getJzmd() {
	return this.jzmd;
    }

    public void setJzmd(BigDecimal jzmd) {
	this.jzmd = jzmd;
    }

    @Column(name = "JZXG", precision = 38, scale = 16)
    public BigDecimal getJzxg() {
	return this.jzxg;
    }

    public void setJzxg(BigDecimal jzxg) {
	this.jzxg = jzxg;
    }

    @Column(name = "ZDSZD", length = 400)
    public String getZdszd() {
	return this.zdszd;
    }

    public void setZdszd(String zdszd) {
	this.zdszd = zdszd;
    }

    @Column(name = "ZDSZN", length = 400)
    public String getZdszn() {
	return this.zdszn;
    }

    public void setZdszn(String zdszn) {
	this.zdszn = zdszn;
    }

    @Column(name = "ZDSZX", length = 400)
    public String getZdszx() {
	return this.zdszx;
    }

    public void setZdszx(String zdszx) {
	this.zdszx = zdszx;
    }

    @Column(name = "ZDSZB", length = 400)
    public String getZdszb() {
	return this.zdszb;
    }

    public void setZdszb(String zdszb) {
	this.zdszb = zdszb;
    }

    @Column(name = "ZDT", length = 4000)
    public String getZdt() {
	return this.zdt;
    }

    public void setZdt(String zdt) {
	this.zdt = zdt;
    }

    @Column(name = "TFH", length = 100)
    public String getTfh() {
	return this.tfh;
    }

    public void setTfh(String tfh) {
	this.tfh = tfh;
    }

    @Column(name = "DJH", length = 40)
    public String getDjh() {
	return this.djh;
    }

    public void setDjh(String djh) {
	this.djh = djh;
    }

    @Column(name = "ZT", length = 4)
    public String getZt() {
	return this.zt;
    }

    public void setZt(String zt) {
	this.zt = zt;
    }

    @Column(name = "RELATIONID", length = 400)
    public String getRelationid() {
	return this.relationid;
    }

    public void setRelationid(String relationid) {
	this.relationid = relationid;
    }

    @Column(name = "GXLX", length = 4)
    public String getGxlx() {
	return this.gxlx;
    }

    public void setGxlx(String gxlx) {
	this.gxlx = gxlx;
    }

}
