package com.supermap.wisdombusiness.framework.model.gxdjk;

// Generated 2016-3-28 10:42:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zrz generated by hbm2java
 */
@Entity
@Table(name = "ZRZ", schema = "GXDJK")
public class Zrz_dj implements java.io.Serializable {

    private String bsm;
    private String bdcdyid;
    private String ysdm;
    private String xmmc;
    private String bdcdyh;
    private String zddm;
    private String zrzh;
    private String zl;
    private String jzwmc;
    private Date jgrq;
    private BigDecimal jzwgd;
    private BigDecimal zzdmj;
    private BigDecimal zydmj;
    private BigDecimal ycjzmj;
    private BigDecimal scjzmj;
    private BigDecimal fdcjyjg;
    private BigDecimal zcs;
    private BigDecimal dscs;
    private BigDecimal dxcs;
    private BigDecimal dxsd;
    private String ghyt;
    private String fwjg;
    private BigDecimal zts;
    private String jzwjbyt;
    private String bz;
    private String zt;
    private String relationid;
    private String gxxmbh;

    public Zrz_dj() {
    }

    public Zrz_dj(String bsm) {
	this.bsm = bsm;
    }

    public Zrz_dj(String bsm, String bdcdyid, String ysdm, String xmmc,
	    String bdcdyh, String zddm, String zrzh, String zl, String jzwmc,
	    Date jgrq, BigDecimal jzwgd, BigDecimal zzdmj, BigDecimal zydmj,
	    BigDecimal ycjzmj, BigDecimal scjzmj, BigDecimal fdcjyjg,
	    BigDecimal zcs, BigDecimal dscs, BigDecimal dxcs, BigDecimal dxsd,
	    String ghyt, String fwjg, BigDecimal zts, String jzwjbyt,
	    String bz, String zt, String relationid, String gxxmbh) {
	this.bsm = bsm;
	this.bdcdyid = bdcdyid;
	this.ysdm = ysdm;
	this.xmmc = xmmc;
	this.bdcdyh = bdcdyh;
	this.zddm = zddm;
	this.zrzh = zrzh;
	this.zl = zl;
	this.jzwmc = jzwmc;
	this.jgrq = jgrq;
	this.jzwgd = jzwgd;
	this.zzdmj = zzdmj;
	this.zydmj = zydmj;
	this.ycjzmj = ycjzmj;
	this.scjzmj = scjzmj;
	this.fdcjyjg = fdcjyjg;
	this.zcs = zcs;
	this.dscs = dscs;
	this.dxcs = dxcs;
	this.dxsd = dxsd;
	this.ghyt = ghyt;
	this.fwjg = fwjg;
	this.zts = zts;
	this.jzwjbyt = jzwjbyt;
	this.bz = bz;
	this.zt = zt;
	this.relationid = relationid;
	this.gxxmbh = gxxmbh;
    }

    @Id
    @Column(name = "BSM", unique = true, nullable = false, length = 200)
    public String getBsm() {
	if (bsm == null) bsm = UUID.randomUUID().toString().replace("-", ""); 
	return this.bsm;
    }

    public void setBsm(String bsm) {
	this.bsm = bsm;
    }

    @Column(name = "BDCDYID", length = 100)
    public String getBdcdyid() {
	return this.bdcdyid;
    }

    public void setBdcdyid(String bdcdyid) {
	this.bdcdyid = bdcdyid;
    }

    @Column(name = "YSDM", length = 20)
    public String getYsdm() {
	return this.ysdm;
    }

    public void setYsdm(String ysdm) {
	this.ysdm = ysdm;
    }

    @Column(name = "XMMC", length = 200)
    public String getXmmc() {
	return this.xmmc;
    }

    public void setXmmc(String xmmc) {
	this.xmmc = xmmc;
    }

    @Column(name = "BDCDYH", length = 100)
    public String getBdcdyh() {
	return this.bdcdyh;
    }

    public void setBdcdyh(String bdcdyh) {
	this.bdcdyh = bdcdyh;
    }

    @Column(name = "ZDDM", length = 38)
    public String getZddm() {
	return this.zddm;
    }

    public void setZddm(String zddm) {
	this.zddm = zddm;
    }

    @Column(name = "ZRZH", length = 100)
    public String getZrzh() {
	return this.zrzh;
    }

    public void setZrzh(String zrzh) {
	this.zrzh = zrzh;
    }

    @Column(name = "ZL", length = 200)
    public String getZl() {
	return this.zl;
    }

    public void setZl(String zl) {
	this.zl = zl;
    }

    @Column(name = "JZWMC", length = 200)
    public String getJzwmc() {
	return this.jzwmc;
    }

    public void setJzwmc(String jzwmc) {
	this.jzwmc = jzwmc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "JGRQ", length = 7)
    public Date getJgrq() {
	return this.jgrq;
    }

    public void setJgrq(Date jgrq) {
	this.jgrq = jgrq;
    }

    @Column(name = "JZWGD", precision = 38, scale = 16)
    public BigDecimal getJzwgd() {
	return this.jzwgd;
    }

    public void setJzwgd(BigDecimal jzwgd) {
	this.jzwgd = jzwgd;
    }

    @Column(name = "ZZDMJ", precision = 38, scale = 16)
    public BigDecimal getZzdmj() {
	return this.zzdmj;
    }

    public void setZzdmj(BigDecimal zzdmj) {
	this.zzdmj = zzdmj;
    }

    @Column(name = "ZYDMJ", precision = 38, scale = 16)
    public BigDecimal getZydmj() {
	return this.zydmj;
    }

    public void setZydmj(BigDecimal zydmj) {
	this.zydmj = zydmj;
    }

    @Column(name = "YCJZMJ", precision = 38, scale = 16)
    public BigDecimal getYcjzmj() {
	return this.ycjzmj;
    }

    public void setYcjzmj(BigDecimal ycjzmj) {
	this.ycjzmj = ycjzmj;
    }

    @Column(name = "SCJZMJ", precision = 38, scale = 16)
    public BigDecimal getScjzmj() {
	return this.scjzmj;
    }

    public void setScjzmj(BigDecimal scjzmj) {
	this.scjzmj = scjzmj;
    }

    @Column(name = "FDCJYJG", precision = 38, scale = 16)
    public BigDecimal getFdcjyjg() {
	return this.fdcjyjg;
    }

    public void setFdcjyjg(BigDecimal fdcjyjg) {
	this.fdcjyjg = fdcjyjg;
    }

    @Column(name = "ZCS", precision = 38, scale = 0)
    public BigDecimal getZcs() {
	return this.zcs;
    }

    public void setZcs(BigDecimal zcs) {
	this.zcs = zcs;
    }

    @Column(name = "DSCS", precision = 38, scale = 0)
    public BigDecimal getDscs() {
	return this.dscs;
    }

    public void setDscs(BigDecimal dscs) {
	this.dscs = dscs;
    }

    @Column(name = "DXCS", precision = 38, scale = 0)
    public BigDecimal getDxcs() {
	return this.dxcs;
    }

    public void setDxcs(BigDecimal dxcs) {
	this.dxcs = dxcs;
    }

    @Column(name = "DXSD", precision = 38, scale = 16)
    public BigDecimal getDxsd() {
	return this.dxsd;
    }

    public void setDxsd(BigDecimal dxsd) {
	this.dxsd = dxsd;
    }

    @Column(name = "GHYT", length = 20)
    public String getGhyt() {
	return this.ghyt;
    }

    public void setGhyt(String ghyt) {
	this.ghyt = ghyt;
    }

    @Column(name = "FWJG", length = 20)
    public String getFwjg() {
	return this.fwjg;
    }

    public void setFwjg(String fwjg) {
	this.fwjg = fwjg;
    }

    @Column(name = "ZTS", precision = 38, scale = 0)
    public BigDecimal getZts() {
	return this.zts;
    }

    public void setZts(BigDecimal zts) {
	this.zts = zts;
    }

    @Column(name = "JZWJBYT", length = 400)
    public String getJzwjbyt() {
	return this.jzwjbyt;
    }

    public void setJzwjbyt(String jzwjbyt) {
	this.jzwjbyt = jzwjbyt;
    }

    @Column(name = "BZ", length = 400)
    public String getBz() {
	return this.bz;
    }

    public void setBz(String bz) {
	this.bz = bz;
    }

    @Column(name = "ZT", length = 20)
    public String getZt() {
	return this.zt;
    }

    public void setZt(String zt) {
	this.zt = zt;
    }

    @Column(name = "RELATIONID", length = 100)
    public String getRelationid() {
	return this.relationid;
    }

    public void setRelationid(String relationid) {
	this.relationid = relationid;
    }

    @Column(name = "GXXMBH", length = 100)
    public String getGxxmbh() {
	return this.gxxmbh;
    }

    public void setGxxmbh(String gxxmbh) {
	this.gxxmbh = gxxmbh;
    }

}
